import type { PlantData } from '../src/types';

export const plantDatabase: PlantData[] = [
  {
    id: 'monstera',
    name: '龟背竹',
    scientificName: 'Monstera deliciosa',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=monstera%20deliciosa%20plant%20in%20white%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '龟背竹是一种常见的室内观叶植物，以其独特的裂叶而闻名。',
    keywords: ['龟背竹', ' monstera', '裂叶', '室内', '观叶'],
    light: '明亮散射光',
    water: '每周1-2次，保持土壤微湿',
    temperature: '18-28°C',
    soil: '疏松透气的腐殖土',
  },
  {
    id: 'pothos',
    name: '绿萝',
    scientificName: 'Epipremnum aureum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=pothos%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '绿萝是最容易养护的室内植物之一，具有空气净化功能。',
    keywords: ['绿萝', 'pothos', '藤蔓', '净化空气', '好养'],
    light: '耐阴，散射光即可',
    water: '土壤干透后浇水，约每周1次',
    temperature: '15-30°C',
    soil: '通用营养土',
  },
  {
    id: 'snake-plant',
    name: '虎皮兰',
    scientificName: 'Sansevieria trifasciata',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=snake%20plant%20sansevieria%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '虎皮兰是一种耐旱耐阴的多肉植物，夜间释放氧气。',
    keywords: ['虎皮兰', 'snake plant', '虎尾兰', '耐旱', '多肉'],
    light: '耐阴，也可适应强光',
    water: '每月1-2次，宁干勿湿',
    temperature: '20-30°C',
    soil: '排水良好的沙质土',
  },
  {
    id: 'peace-lily',
    name: '白掌',
    scientificName: 'Spathiphyllum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=peace%20lily%20spathiphyllum%20with%20white%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '白掌又称一帆风顺，能有效净化室内空气。',
    keywords: ['白掌', 'peace lily', '一帆风顺', '开花', '净化'],
    light: '明亮散射光，避免直射',
    water: '保持土壤湿润，每周2次',
    temperature: '20-28°C',
    soil: '疏松肥沃的腐殖土',
  },
  {
    id: 'succulent',
    name: '多肉植物',
    scientificName: 'Succulent',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=colorful%20succulent%20collection%20in%20small%20pots%20on%20white%20background%20high%20quality&image_size=square',
    description: '多肉植物种类繁多，形态各异，非常耐旱。',
    keywords: ['多肉', 'succulent', '肉肉', '耐旱', '可爱'],
    light: '充足阳光',
    water: '2-4周1次，干透浇透',
    temperature: '15-28°C',
    soil: '多肉专用颗粒土',
  },
  {
    id: 'cactus',
    name: '仙人掌',
    scientificName: 'Cactaceae',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cactus%20in%20terracotta%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '仙人掌是沙漠植物，极其耐旱，有些会开花。',
    keywords: ['仙人掌', 'cactus', '仙人球', '沙漠', '耐旱'],
    light: '充足阳光',
    water: '每月1次或更少',
    temperature: '20-35°C',
    soil: '仙人掌专用沙质土',
  },
  {
    id: 'orchid',
    name: '兰花',
    scientificName: 'Orchidaceae',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=phalaenopsis%20orchid%20with%20purple%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '兰花是高雅的观赏植物，花期长，香气宜人。',
    keywords: ['兰花', 'orchid', '蝴蝶兰', '高雅', '开花'],
    light: '明亮散射光',
    water: '每周1次，保持通风',
    temperature: '18-28°C',
    soil: '兰花专用水苔或树皮',
  },
  {
    id: 'aloe-vera',
    name: '芦荟',
    scientificName: 'Aloe vera',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=aloe%20vera%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '芦荟不仅观赏价值高，还有药用和美容功效。',
    keywords: ['芦荟', 'aloe', '药用', '美容', '耐旱'],
    light: '明亮散射光',
    water: '土壤干透后浇水',
    temperature: '15-30°C',
    soil: '排水良好的沙质土',
  },
  {
    id: 'ficus',
    name: '橡皮树',
    scientificName: 'Ficus elastica',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ficus%20elastica%20rubber%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '橡皮树叶片宽大，有光泽，是优秀的室内观叶植物。',
    keywords: ['橡皮树', 'ficus', '橡胶树', '大叶', '观叶'],
    light: '明亮散射光',
    water: '土壤表面干燥后浇水',
    temperature: '18-28°C',
    soil: '肥沃疏松的腐殖土',
  },
  {
    id: 'spider-plant',
    name: '吊兰',
    scientificName: 'Chlorophytum comosum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=spider%20plant%20chlorophytum%20in%20hanging%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '吊兰生长迅速，能有效净化空气，适合悬挂养护。',
    keywords: ['吊兰', 'spider plant', '垂吊', '净化空气', '好养'],
    light: '明亮散射光',
    water: '保持土壤微湿',
    temperature: '15-28°C',
    soil: '通用营养土',
  },
  {
    id: 'zz-plant',
    name: '金钱树',
    scientificName: 'Zamioculcas zamiifolia',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=zz%20plant%20zamioculcas%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '金钱树寓意招财，叶片肥厚有光泽，非常耐阴耐旱。',
    keywords: ['金钱树', 'zz plant', '招财', '耐阴', '耐旱'],
    light: '耐阴，散射光即可',
    water: '2-3周1次，宁干勿湿',
    temperature: '18-30°C',
    soil: '排水良好的营养土',
  },
  {
    id: 'boston-fern',
    name: '波士顿蕨',
    scientificName: 'Nephrolepis exaltata',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=boston%20fern%20in%20hanging%20basket%20on%20white%20background%20high%20quality&image_size=square',
    description: '波士顿蕨是天然的加湿器，能增加室内空气湿度。',
    keywords: ['波士顿蕨', 'fern', '蕨类', '加湿', '翠绿'],
    light: '明亮散射光',
    water: '保持土壤湿润，经常喷水',
    temperature: '18-25°C',
    soil: '疏松透气的腐殖土',
  },
  {
    id: 'chinese-evergreen',
    name: '广东万年青',
    scientificName: 'Aglaonema',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=aglaonema%20chinese%20evergreen%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '广东万年青叶色美丽，耐阴性强，适合室内摆放。',
    keywords: ['广东万年青', 'aglaonema', '万年青', '耐阴', '美丽'],
    light: '耐阴，避免强光',
    water: '保持土壤微湿',
    temperature: '20-30°C',
    soil: '疏松肥沃的腐殖土',
  },
  {
    id: 'weeping-fig',
    name: '垂叶榕',
    scientificName: 'Ficus benjamina',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ficus%20benjamina%20weeping%20fig%20tree%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '垂叶榕是常见的室内大型绿植，树形优美。',
    keywords: ['垂叶榕', 'weeping fig', '榕树', '大型', '室内'],
    light: '明亮散射光',
    water: '土壤表面干燥后浇水',
    temperature: '18-28°C',
    soil: '肥沃的营养土',
  },
  {
    id: 'lucky-bamboo',
    name: '富贵竹',
    scientificName: 'Dracaena sanderiana',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=lucky%20bamboo%20dracaena%20in%20glass%20vase%20with%20water%20on%20white%20background%20high%20quality&image_size=square',
    description: '富贵竹寓意吉祥，可水培或土培，非常好养。',
    keywords: ['富贵竹', 'lucky bamboo', '开运竹', '水培', '吉祥'],
    light: '明亮散射光',
    water: '水培每周换水，土培保持湿润',
    temperature: '20-30°C',
    soil: '水培或疏松营养土',
  },
  {
    id: 'jade-plant',
    name: '玉树',
    scientificName: 'Crassula ovata',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=jade%20plant%20crassula%20ovata%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '玉树又称发财树，叶片圆润厚实，寓意美好。',
    keywords: ['玉树', 'jade plant', '发财树', '多肉', '好养'],
    light: '充足阳光',
    water: '土壤干透后浇水',
    temperature: '15-28°C',
    soil: '排水良好的沙质土',
  },
  {
    id: 'ponytail-palm',
    name: '酒瓶兰',
    scientificName: 'Beaucarnea recurvata',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ponytail%20palm%20beaucarnea%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '酒瓶兰造型独特，茎干膨大储存水分，非常耐旱。',
    keywords: ['酒瓶兰', 'ponytail palm', '独特', '耐旱', '观叶'],
    light: '充足阳光',
    water: '2-3周1次',
    temperature: '18-30°C',
    soil: '排水良好的沙质土',
  },
  {
    id: 'swiss-cheese',
    name: '龟背竹（迷你）',
    scientificName: 'Monstera adansonii',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=monstera%20adansonii%20swiss%20cheese%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '迷你龟背竹叶片孔洞更密集，适合悬挂或攀爬养护。',
    keywords: ['迷你龟背竹', 'swiss cheese', '洞洞芋', '攀爬', '可爱'],
    light: '明亮散射光',
    water: '保持土壤微湿',
    temperature: '18-28°C',
    soil: '疏松透气的腐殖土',
  },
  {
    id: 'bird-of-paradise',
    name: '鹤望兰',
    scientificName: 'Strelitzia reginae',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=bird%20of%20paradise%20strelitzia%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '鹤望兰花朵形似仙鹤，叶片宽大，是高档室内绿植。',
    keywords: ['鹤望兰', 'bird of paradise', '天堂鸟', '高档', '开花'],
    light: '充足阳光',
    water: '土壤表面干燥后浇水',
    temperature: '18-30°C',
    soil: '肥沃疏松的营养土',
  },
  {
    id: 'philodendron',
    name: '蔓绿绒',
    scientificName: 'Philodendron',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=philodendron%20heart%20leaf%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '蔓绿绒品种繁多，叶片优美，适合新手养护。',
    keywords: ['蔓绿绒', 'philodendron', '喜林芋', '观叶', '好养'],
    light: '明亮散射光',
    water: '保持土壤微湿',
    temperature: '18-30°C',
    soil: '疏松的腐殖土',
  },
  {
    id: 'calathea',
    name: '竹芋',
    scientificName: 'Calathea',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=calathea%20ornata%20pinstripe%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '竹芋叶片花纹美丽，被称为"观叶植物之王"。',
    keywords: ['竹芋', 'calathea', '美丽', '花纹', '观叶'],
    light: '明亮散射光',
    water: '保持土壤湿润，软水最佳',
    temperature: '20-28°C',
    soil: '疏松透气的腐殖土',
  },
  {
    id: 'croton',
    name: '变叶木',
    scientificName: 'Codiaeum variegatum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=croton%20plant%20with%20colorful%20leaves%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '变叶木叶色丰富多彩，是室内色彩最丰富的植物之一。',
    keywords: ['变叶木', 'croton', '洒金榕', '彩色', '观叶'],
    light: '充足阳光',
    water: '保持土壤微湿',
    temperature: '20-30°C',
    soil: '肥沃的营养土',
  },
  {
    id: 'dracaena',
    name: '龙血树',
    scientificName: 'Dracaena marginata',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dracaena%20marginata%20dragon%20tree%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '龙血树造型优雅，耐旱耐阴，适合室内摆放。',
    keywords: ['龙血树', 'dracaena', '千年木', '优雅', '耐阴'],
    light: '明亮散射光',
    water: '土壤干透后浇水',
    temperature: '18-30°C',
    soil: '疏松的营养土',
  },
  {
    id: 'pilea',
    name: '镜面草',
    scientificName: 'Pilea peperomioides',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=pilea%20peperomioides%20chinese%20money%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '镜面草叶片圆润似铜钱，又称"中国金钱草"。',
    keywords: ['镜面草', 'pilea', '铜钱草', '可爱', '网红'],
    light: '明亮散射光',
    water: '土壤表面干燥后浇水',
    temperature: '15-28°C',
    soil: '疏松透气的营养土',
  },
  {
    id: 'peperomia',
    name: '椒草',
    scientificName: 'Peperomia',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=peperomia%20obtusifolia%20baby%20rubber%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '椒草品种繁多，叶片肥厚可爱，适合桌面摆放。',
    keywords: ['椒草', 'peperomia', '豆瓣绿', '可爱', '桌面'],
    light: '明亮散射光',
    water: '土壤干透后浇水',
    temperature: '18-28°C',
    soil: '疏松透气的营养土',
  },
  {
    id: 'rose',
    name: '月季',
    scientificName: 'Rosa hybrida',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=rose%20plant%20with%20pink%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '月季被称为"花中皇后"，花期长，花色丰富。',
    keywords: ['月季', 'rose', '玫瑰', '开花', '阳台'],
    light: '充足阳光，每天6小时以上',
    water: '保持土壤湿润，避免积水',
    temperature: '15-28°C',
    soil: '肥沃疏松的微酸性土',
  },
  {
    id: 'jasmine',
    name: '茉莉花',
    scientificName: 'Jasminum sambac',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=jasmine%20plant%20with%20white%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '茉莉花香气浓郁，花朵洁白，是著名的芳香植物。',
    keywords: ['茉莉', 'jasmine', '芳香', '开花', '白色'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '20-35°C',
    soil: '肥沃的微酸性土',
  },
  {
    id: 'gardenia',
    name: '栀子花',
    scientificName: 'Gardenia jasminoides',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=gardenia%20plant%20with%20white%20fragrant%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '栀子花香气怡人，花朵洁白如玉，非常受喜爱。',
    keywords: ['栀子', 'gardenia', '芳香', '白色', '开花'],
    light: '充足阳光',
    water: '保持土壤湿润，软水最佳',
    temperature: '18-28°C',
    soil: '酸性腐殖土',
  },
  {
    id: 'lavender',
    name: '薰衣草',
    scientificName: 'Lavandula',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=lavender%20plant%20with%20purple%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '薰衣草香气宜人，有舒缓安神的功效。',
    keywords: ['薰衣草', 'lavender', '芳香', '紫色', '香草'],
    light: '充足阳光',
    water: '土壤干透后浇水',
    temperature: '15-25°C',
    soil: '排水良好的碱性沙质土',
  },
  {
    id: 'rosemary',
    name: '迷迭香',
    scientificName: 'Salvia rosmarinus',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=rosemary%20herb%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '迷迭香是芳香植物，可用于烹饪，有提神功效。',
    keywords: ['迷迭香', 'rosemary', '香草', '烹饪', '芳香'],
    light: '充足阳光',
    water: '土壤干透后浇水',
    temperature: '15-28°C',
    soil: '排水良好的沙质土',
  },
  {
    id: 'basil',
    name: '罗勒',
    scientificName: 'Ocimum basilicum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=basil%20herb%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '罗勒是常用的烹饪香草，又称九层塔。',
    keywords: ['罗勒', 'basil', '九层塔', '香草', '烹饪'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '20-30°C',
    soil: '肥沃疏松的营养土',
  },
  {
    id: 'mint',
    name: '薄荷',
    scientificName: 'Mentha',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=mint%20herb%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '薄荷清凉提神，可用于饮品和烹饪，生长迅速。',
    keywords: ['薄荷', 'mint', '香草', '清凉', '好养'],
    light: '充足阳光或半阴',
    water: '保持土壤湿润',
    temperature: '15-30°C',
    soil: '肥沃湿润的土壤',
  },
  {
    id: 'tomato',
    name: '番茄',
    scientificName: 'Solanum lycopersicum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cherry%20tomato%20plant%20in%20pot%20with%20red%20fruits%20on%20white%20background%20high%20quality&image_size=square',
    description: '番茄是最受欢迎的家庭蔬菜之一，适合阳台种植。',
    keywords: ['番茄', 'tomato', '西红柿', '蔬菜', '阳台'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '20-30°C',
    soil: '肥沃的营养土',
  },
  {
    id: 'chili',
    name: '辣椒',
    scientificName: 'Capsicum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=chili%20pepper%20plant%20in%20pot%20with%20red%20peppers%20on%20white%20background%20high%20quality&image_size=square',
    description: '辣椒品种繁多，适合家庭种植，观赏食用两相宜。',
    keywords: ['辣椒', 'chili', '蔬菜', '调味', '阳台'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '20-32°C',
    soil: '肥沃疏松的营养土',
  },
  {
    id: 'lettuce',
    name: '生菜',
    scientificName: 'Lactuca sativa',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=lettuce%20growing%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '生菜生长迅速，适合阳台盆栽，随吃随摘。',
    keywords: ['生菜', 'lettuce', '蔬菜', '叶菜', '阳台'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '15-22°C',
    soil: '肥沃疏松的营养土',
  },
  {
    id: 'strawberry',
    name: '草莓',
    scientificName: 'Fragaria × ananassa',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=strawberry%20plant%20in%20pot%20with%20ripe%20strawberries%20on%20white%20background%20high%20quality&image_size=square',
    description: '草莓适合家庭盆栽，果实鲜美，花果同赏。',
    keywords: ['草莓', 'strawberry', '水果', '阳台', '可爱'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '15-25°C',
    soil: '肥沃疏松的微酸性土',
  },
  {
    id: 'lemon-tree',
    name: '柠檬树',
    scientificName: 'Citrus limon',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dwarf%20lemon%20tree%20in%20pot%20with%20lemons%20on%20white%20background%20high%20quality&image_size=square',
    description: '柠檬树可盆栽观赏，果实可食用，花香宜人。',
    keywords: ['柠檬', 'lemon', '果树', '盆栽', '芳香'],
    light: '充足阳光',
    water: '保持土壤微湿',
    temperature: '18-30°C',
    soil: '肥沃的微酸性土',
  },
  {
    id: 'bonsai',
    name: '盆景',
    scientificName: 'Bonsai',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=traditional%20bonsai%20tree%20in%20ceramic%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '盆景是中国传统艺术，通过修剪造型展现自然之美。',
    keywords: ['盆景', 'bonsai', '造型', '艺术', '传统'],
    light: '根据树种而定',
    water: '根据树种而定',
    temperature: '根据树种而定',
    soil: '排水良好的专用土',
  },
  {
    id: 'fern',
    name: '蕨类植物',
    scientificName: 'Pteridophyta',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=green%20fern%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '蕨类植物叶片翠绿飘逸，喜欢高湿度环境。',
    keywords: ['蕨类', 'fern', '翠绿', '喜湿', '观叶'],
    light: '明亮散射光',
    water: '保持土壤湿润，经常喷水',
    temperature: '18-25°C',
    soil: '疏松透气的腐殖土',
  },
  {
    id: 'ivy',
    name: '常春藤',
    scientificName: 'Hedera helix',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=english%20ivy%20plant%20in%20hanging%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '常春藤是经典的攀缘植物，四季常青，寓意美好。',
    keywords: ['常春藤', 'ivy', '攀缘', '常青', '垂吊'],
    light: '明亮散射光',
    water: '保持土壤微湿',
    temperature: '15-25°C',
    soil: '肥沃疏松的营养土',
  },
  {
    id: 'bamboo',
    name: '竹子',
    scientificName: 'Bambusoideae',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=lucky%20bamboo%20plant%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '竹子象征高洁正直，适合庭院或大型盆栽。',
    keywords: ['竹子', 'bamboo', '庭院', '高洁', '观叶'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '15-30°C',
    soil: '肥沃深厚的土壤',
  },
  {
    id: 'hydrangea',
    name: '绣球花',
    scientificName: 'Hydrangea macrophylla',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hydrangea%20plant%20with%20blue%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '绣球花花团锦簇，花色可随土壤酸碱度变化。',
    keywords: ['绣球', 'hydrangea', '八仙花', '开花', '庭院'],
    light: '半阴环境',
    water: '保持土壤湿润',
    temperature: '15-25°C',
    soil: '肥沃的腐殖土',
  },
  {
    id: 'camellia',
    name: '山茶花',
    scientificName: 'Camellia japonica',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=camellia%20plant%20with%20pink%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '山茶花是中国传统名花，花期在冬季至早春。',
    keywords: ['山茶', 'camellia', '传统名花', '冬季开花', '贵重'],
    light: '半阴环境',
    water: '保持土壤湿润',
    temperature: '10-20°C',
    soil: '酸性腐殖土',
  },
  {
    id: 'azalea',
    name: '杜鹃花',
    scientificName: 'Rhododendron simsii',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=azalea%20plant%20with%20red%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '杜鹃花开花繁茂，色彩丰富，是著名的观赏花卉。',
    keywords: ['杜鹃', 'azalea', '映山红', '开花', '观赏'],
    light: '明亮散射光',
    water: '保持土壤湿润',
    temperature: '12-25°C',
    soil: '酸性腐殖土',
  },
  {
    id: 'geranium',
    name: '天竺葵',
    scientificName: 'Pelargonium',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=geranium%20plant%20with%20red%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '天竺葵花期长，花色丰富，适合阳台养护。',
    keywords: ['天竺葵', 'geranium', '洋绣球', '开花', '阳台'],
    light: '充足阳光',
    water: '土壤表面干燥后浇水',
    temperature: '15-25°C',
    soil: '排水良好的营养土',
  },
  {
    id: 'petunia',
    name: '矮牵牛',
    scientificName: 'Petunia',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=petunia%20plant%20with%20purple%20flowers%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '矮牵牛开花繁茂，色彩丰富，是阳台和花园的宠儿。',
    keywords: ['矮牵牛', 'petunia', '碧冬茄', '开花', '阳台'],
    light: '充足阳光',
    water: '保持土壤湿润',
    temperature: '15-28°C',
    soil: '肥沃疏松的营养土',
  },
  {
    id: 'succulent-rose',
    name: '山地玫瑰',
    scientificName: 'Aeonium aureum',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=greenovia%20mountain%20rose%20succulent%20in%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '山地玫瑰形似玫瑰花，是多肉植物中的热门品种。',
    keywords: ['山地玫瑰', 'succulent rose', '多肉', '玫瑰', '网红'],
    light: '充足阳光',
    water: '土壤干透后浇水',
    temperature: '15-25°C',
    soil: '多肉专用颗粒土',
  },
  {
    id: 'string-of-pearls',
    name: '珍珠吊兰',
    scientificName: 'Curio rowleyanus',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=string%20of%20pearls%20succulent%20in%20hanging%20pot%20on%20white%20background%20high%20quality&image_size=square',
    description: '珍珠吊兰叶片圆润如珍珠，适合悬挂养护。',
    keywords: ['珍珠吊兰', 'string of pearls', '佛珠', '多肉', '垂吊'],
    light: '明亮散射光',
    water: '土壤干透后浇水',
    temperature: '15-25°C',
    soil: '排水良好的颗粒土',
  },
  {
    id: 'air-plant',
    name: '空气凤梨',
    scientificName: 'Tillandsia',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=tillandsia%20air%20plant%20on%20driftwood%20on%20white%20background%20high%20quality&image_size=square',
    description: '空气凤梨无需土壤，可直接从空气中吸收水分和养分。',
    keywords: ['空气凤梨', 'air plant', '无土', '奇特', '好养'],
    light: '明亮散射光',
    water: '每周喷水2-3次',
    temperature: '15-30°C',
    soil: '无需土壤',
  },
];

export default plantDatabase;
