import { ColorStop, GradientType, generateGradientCss } from './colorUtils';

export function generateBackgroundCss(
  stops: ColorStop[],
  angle: number,
  type: GradientType
): string {
  const gradient = generateGradientCss(stops, angle, type);
  return `.gradient-element {
  background: ${gradient};
}`;
}

export function generateFullCss(
  stops: ColorStop[],
  angle: number,
  type: GradientType
): string {
  const gradient = generateGradientCss(stops, angle, type);
  return `/* CSS Gradient Generated by Gradient Generator */
.element {
  width: 100%;
  height: 100%;
  background: ${gradient};
  /* Fallback for old browsers */
  background: ${gradient};
}`;
}

export function formatCodeWithLineNumbers(code: string): { line: number; content: string }[] {
  const lines = code.split('\n');
  return lines.map((content, index) => ({
    line: index + 1,
    content
  }));
}

export function getCssPropertyValue(
  stops: ColorStop[],
  angle: number,
  type: GradientType
): string {
  return generateGradientCss(stops, angle, type);
}
