export const CONFIG = {
  PLAYER: {
    BASE_WIDTH: 40,
    BASE_HEIGHT: 30,
    OFFSET_RATIO: 0.4,
    WARN_DISTANCE: 50,
    HALO_MIN_LEVEL: 1
  },

  STAR_TRAIL: {
    NODE_RADIUS: 12,
    NODE_SPACING: 40,
    PULSE_PERIOD: 1200,
    HUE: 180,
    MIN_AMPLITUDE: 30,
    MAX_AMPLITUDE: 60,
    MIN_WAVELENGTH: 150,
    MAX_WAVELENGTH: 200,
    TRAIL_LENGTH: 30,
    SEGMENT_COUNT: 3
  },

  SPEED: {
    INITIAL: 100,
    MAX: 250,
    INCREASE_INTERVAL: 30000,
    INCREASE_RATE: 0.1,
    SLOW_DURATION: 1500,
    SLOW_MULTIPLIER: 0.5
  },

  STAR: {
    RADIUS: 12,
    BASE_SCORE: 5,
    COMPENSATION_SCORE: 2,
    PARTICLE_MIN: 15,
    PARTICLE_MAX: 25,
    PARTICLE_MIN_SIZE: 2,
    PARTICLE_MAX_SIZE: 5,
    PARTICLE_DURATION: 800
  },

  VOID: {
    RADIUS: 25,
    PENALTY_SCORE: 3,
    SHOCK_DURATION: 300,
    MAX_HITS: 3
  },

  COMBO: {
    STARS_PER_LEVEL: 10,
    INCREASE_PER_LEVEL: 0.5,
    MAX_MULTIPLIER: 3,
    BASE_MULTIPLIER: 1
  },

  SPAWN: {
    INITIAL_INTERVAL: 2000,
    MIN_INTERVAL: 800,
    INITIAL_VOID_CHANCE: 0.2,
    MAX_VOID_CHANCE: 0.4,
    SPEED_FLASH_DURATION: 100
  },

  NEBULA: {
    PARTICLE_MIN_SIZE: 2,
    PARTICLE_MAX_SIZE: 8,
    MIN_ALPHA: 0.2,
    MAX_ALPHA: 0.5,
    ROTATION_SPEED: 0.0002,
    PARTICLE_COUNT: 150
  },

  UI: {
    MIN_FONT_SIZE: 16,
    MIN_BUTTON_SIZE: 40,
    FLOAT_DURATION: 500,
    CARD_BLUR: 10
  },

  PARTICLE_LIMIT: 500,
  COLLISION_LIMIT: 100
};

export type ConfigType = typeof CONFIG;
