const DICTIONARY_RAW: string[] = [
  'ability','able','about','above','accept','according','account','across','action','activity',
  'actually','address','administration','admit','adult','affect','after','again','against','age',
  'agency','agent','ago','agree','agreement','ahead','allow','almost','alone','along',
  'already','also','although','always','American','among','amount','analysis','animal','another',
  'answer','anyone','anything','appear','apply','approach','area','argue','around','arrive',
  'article','artist','assume','attack','attention','audience','author','authority','available','avoid',
  'aware','away','baby','back','bank','base','beautiful','because','become','before',
  'begin','behavior','behind','believe','benefit','best','better','between','beyond','bill',
  'billion','black','blood','board','body','book','born','both','break','bring',
  'brother','budget','build','building','business','call','camera','campaign','cancer','candidate',
  'capital','car','card','care','career','carry','case','catch','cause','cell',
  'center','central','century','certain','certainly','chair','challenge','chance','change','character',
  'charge','check','child','choice','choose','church','citizen','city','civil','claim',
  'class','clear','clearly','close','coach','cold','collection','college','color','come',
  'commercial','common','community','company','compare','computer','concern','condition','conference','Congress',
  'consider','consumer','contain','continue','control','cost','could','country','couple','course',
  'court','cover','create','crime','cultural','culture','current','customer','dark','data',
  'daughter','dead','deal','death','debate','decade','decide','decision','deep','defense',
  'degree','Democrat','democratic','describe','design','despite','detail','determine','develop','difference',
  'different','difficult','dinner','direction','director','discover','discuss','discussion','disease','doctor',
  'door','down','draw','dream','drive','drop','drug','during','each','early',
  'east','easy','economic','economy','edge','education','effect','effort','eight','either',
  'election','else','employee','energy','enjoy','enough','enter','entire','environment','especially',
  'establish','even','evening','event','ever','every','everybody','everyone','everything','evidence',
  'exactly','example','executive','exist','expect','experience','expert','explain','face','fact',
  'factor','fail','fall','family','fast','father','fear','federal','feel','field',
  'fight','figure','fill','film','final','finally','financial','find','fine','finger',
  'finish','fire','firm','first','fish','five','floor','fly','follow','food',
  'foot','force','foreign','forget','form','former','forward','four','free','friend',
  'from','front','full','fund','future','game','garden','gas','general','generation',
  'girl','give','glass','goal','good','government','great','green','ground','group',
  'grow','growth','guess','hair','half','hand','hang','happen','happy','hard',
  'have','head','health','hear','heart','heat','heavy','help','here','herself',
  'high','himself','history','hold','home','hope','hospital','hotel','hour','house',
  'however','huge','human','hundred','husband','idea','identify','image','imagine','impact',
  'important','improve','include','including','increase','indeed','indicate','individual','industry','information',
  'inside','instead','institution','interest','interesting','international','interview','into','investment','issue',
  'item','itself','job','join','just','keep','kill','kind','kitchen','know',
  'knowledge','land','language','large','last','late','later','laugh','lawyer','lead',
  'leader','learn','least','leave','left','legal','level','life','light','like',
  'likely','line','list','listen','little','live','local','long','look','lose',
  'loss','machine','magazine','main','maintain','major','majority','make','manage','management',
  'manager','many','market','marriage','material','matter','maybe','mean','measure','media',
  'medical','meeting','member','memory','mention','message','method','middle','might','military',
  'million','mind','minute','miss','mission','mistake','model','modern','moment','money',
  'month','more','morning','most','mother','mouth','move','movement','movie','music',
  'must','myself','name','nation','national','natural','nature','near','nearly','necessary',
  'need','network','never','news','newspaper','next','nice','night','none','north',
  'note','nothing','notice','number','occur','offer','office','officer','official','often',
  'once','only','onto','open','operation','opportunity','option','order','organization','others',
  'outside','owner','page','pain','painting','paper','parent','part','participant','particular',
  'particularly','partner','party','pass','past','patient','pattern','peace','people','perform',
  'performance','perhaps','period','person','personal','phone','physical','pick','picture','piece',
  'place','plan','plant','play','player','please','point','police','policy','political',
  'politics','poor','popular','population','position','positive','possible','power','practice','prepare',
  'present','president','pressure','pretty','prevent','price','private','probably','problem','process',
  'produce','product','production','professional','professor','program','project','property','protect','prove',
  'provide','public','pull','purpose','push','quality','question','quick','quickly','quite',
  'race','radio','raise','range','rate','rather','reach','ready','real','reality',
  'realize','really','reason','receive','recent','recently','recognize','record','reflect','region',
  'relate','relationship','religious','remain','remember','remove','report','represent','Republic','require',
  'research','resource','respond','response','rest','result','return','reveal','rich','right',
  'rise','risk','road','rock','role','room','rule','safe','same','save',
  'scene','school','science','scientist','score','season','seat','second','section','security',
  'seek','seem','sell','send','senior','sense','series','serious','serve','service',
  'seven','several','shake','share','shoot','short','shot','should','shoulder','show',
  'side','sign','significant','similar','simple','simply','since','sing','single','sister',
  'site','situation','size','skill','skin','small','smile','social','society','soldier',
  'some','somebody','someone','something','sometimes','son','song','soon','sort','sound',
  'source','south','southern','space','speak','special','specific','speech','spend','sport',
  'spring','staff','stage','stand','standard','star','start','state','statement','station',
  'stay','step','still','stock','stop','story','strategy','street','strong','structure',
  'student','study','stuff','style','subject','success','successful','such','suddenly','suffer',
  'suggest','summer','support','sure','surface','system','table','take','talk','task',
  'teacher','team','technology','television','tell','tend','term','test','thank','that',
  'their','them','then','theory','there','therefore','they','thing','think','third',
  'this','those','though','thought','thousand','threat','three','through','throughout','throw',
  'thus','time','today','together','tonight','total','tough','toward','town','trade',
  'traditional','training','travel','treat','treatment','tree','trial','trip','trouble','true',
  'truth','turn','type','under','understand','unit','until','upon','usually','value',
  'various','very','victim','view','violence','visit','voice','vote','wait','walk',
  'wall','want','watch','water','weapon','wear','week','weight','well','west',
  'western','what','whatever','when','where','whether','which','while','white','whole',
  'whom','whose','wide','wife','will','wind','window','wish','with','within',
  'without','woman','wonder','word','work','worker','world','worry','would','write',
  'writer','wrong','yard','year','young','yourself',
  'tiger','lion','eagle','shark','horse','mouse','sheep','snake','whale','zebra',
  'panda','koala','raven','crane','goose','otter','beach','cloud','storm','frost',
  'thunder','lightning','breeze','drizzle','sunrise','sunset','rainbow','planet','comet','meteor',
  'galaxy','nebula','rocket','satellite','robot','laptop','tablet','camera','sensor','display',
  'battery','network','wireless','digital','virtual','augment','quantum','biology','physics','chemistry',
  'genome','protein','enzyme','molecule','compound','element','isotope','crystal','polymer','elastic',
  'gravity','inertia','momentum','quantum','electron','neutron','proton','photon','neutrino','quark',
  'forest','jungle','desert','tundra','wetland','meadow','prairie','savanna','glacier','volcano',
  'island','canyon','valley','plateau','basin','delta','fjord','lagoon','reef','cove',
  'piano','guitar','violin','cello','flute','trumpet','drum','harp','saxophone','clarinet',
  'symphony','melody','rhythm','harmony','chorus','ballad','sonata','concerto','opera','ballet',
  'novel','poem','essay','biography','fiction','memoir','chapter','verse','stanza','prose',
  'author','editor','reader','critic','publisher','library','archive','manuscript','folklore','mythology',
  'pizza','pasta','burger','sushi','salad','steak','curry','tacos','ramen','waffle',
  'pancake','croissant','bagel','yogurt','smoothie','espresso','cappuccino','macaron','truffle','caramel',
  'soccer','tennis','hockey','rugby','boxing','archery','fencing','rowing','cycling','skiing',
  'surfing','diving','climbing','marathon','sprint','relay','medal','trophy','stadium','arena',
  'kitchen','bedroom','bathroom','garage','balcony','corridor','cellar','attic','porch','chimney',
  'faucet','cabinet','wardrobe','cushion','blanket','curtain','chandelier','fireplace','bookshelf','wardrobe',
  'castle','palace','temple','mosque','church','cathedral','museum','library','theater','stadium',
  'bridge','tunnel','highway','railway','airport','harbor','canal','aqueduct','skyscraper','monument',
  'engineer','architect','surgeon','dentist','pharmacist','veterinarian','astronomer','geologist','botanist','zoologist',
  'journalist','designer','producer','director','inventor','explorer','missionary','diplomat','ambassador','magistrate'
];

const DICTIONARY: Set<string> = new Set(DICTIONARY_RAW.map((w) => w.toUpperCase()));

export function validate(word: string): boolean {
  if (!word || word.length < 2) return false;
  return DICTIONARY.has(word.toUpperCase());
}

export function calculateScore(word: string): number {
  return word.length * 10;
}

export function getDictionarySize(): number {
  return DICTIONARY.size;
}
