const fs = require('fs');
const path = require('path');

const adminPanelCode = [
  "import { useState } from 'react';",
  "import { useNavigate } from 'react-router-dom';",
  "import { useApp } from '../App';",
  "import { Category } from '../types';",
  "",
  "const AdminPanel = () => {",
  "  const { markets, addMarket, bookStall, cancelStall, user } = useApp();",
  "  const navigate = useNavigate();",
  "  const [name, setName] = useState('');",
  "  const [date, setDate] = useState('');",
  "  const [deadline, setDeadline] = useState('');",
  "  const [expandedMarket, setExpandedMarket] = useState<string | null>(null);",
  "",
  "  if (!user || !user.isAdmin) {",
  "    return (",
  "      <div style={{ padding: '40px', textAlign: 'center' }} className=\"fade-in\">",
  "        <h2 style={{ color: '#4a148c', marginBottom: '16px' }}>无权限访问</h2>",
  "        <p style={{ color: '#7b1fa2', marginBottom: '20px' }}>请使用管理员账号登录</p>",
  "        <button onClick={() => navigate('/')}>返回首页</button>",
  "      </div>",
  "    );",
  "  }",
  "",
  "  const handleCreateMarket = () => {",
  "    if (!name.trim() || !date || !deadline) {",
  "      alert('请填写所有字段');",
  "      return;",
  "    }",
  "    addMarket(name, date, deadline);",
  "    setName('');",
  "    setDate('');",
  "    setDeadline('');",
  "  };",
  "",
  "  const handleToggleStall = (marketId: string, stallId: number, isBooked: boolean) => {",
  "    if (isBooked) {",
  "      cancelStall(marketId, stallId);",
  "    } else {",
  "      bookStall(marketId, stallId, '其他' as Category, '管理员手动标记', 'admin');",
  "    }",
  "  };",
  "",
  "  const totalStalls = markets.reduce((sum, m) => sum + m.totalStalls, 0);",
  "  const bookedStalls = markets.reduce((sum, m) => sum + m.stalls.filter(s => s.booked).length, 0);",
  "  const totalFeedbacks = markets.reduce((sum, m) => sum + m.feedbacks.length, 0);",
  "",
  "  return (",
  "    <div className=\"admin-panel fade-in\">",
  "      <h2>管理员后台</h2>",
  "",
  "      <div className=\"admin-section\">",
  "        <h3>统计概览</h3>",
  "        <div style={{ display: 'flex', gap: '32px', flexWrap: 'wrap' }}>",
  "          <div>",
  "            <div style={{ fontSize: '13px', color: '#7b1fa2' }}>市场总数</div>",
  "            <div style={{ fontSize: '28px', fontWeight: 700, color: '#4a148c' }}>{markets.length}</div>",
  "          </div>",
  "          <div>",
  "            <div style={{ fontSize: '13px', color: '#7b1fa2' }}>总摊位数</div>",
  "            <div style={{ fontSize: '28px', fontWeight: 700, color: '#4a148c' }}>{totalStalls}</div>",
  "          </div>",
  "          <div>",
  "            <div style={{ fontSize: '13px', color: '#7b1fa2' }}>已预订摊位</div>",
  "            <div style={{ fontSize: '28px', fontWeight: 700, color: '#ec407a' }}>{bookedStalls}</div>",
  "          </div>",
  "          <div>",
  "            <div style={{ fontSize: '13px', color: '#7b1fa2' }}>评价总数</div>",
  "            <div style={{ fontSize: '28px', fontWeight: 700, color: '#ab47bc' }}>{totalFeedbacks}</div>",
  "          </div>",
  "        </div>",
  "      </div>",
  "",
  "      <div className=\"admin-section\">",
  "        <h3>创建新市场</h3>",
  "        <div className=\"admin-form\">",
  "          <div className=\"admin-form-row\">",
  "            <label>活动名称</label>",
  "            <input type=\"text\" value={name} onChange={e => setName(e.target.value)} placeholder=\"请输入活动名称\" />",
  "          </div>",
  "          <div className=\"admin-form-row\">",
  "            <label>活动日期</label>",
  "            <input type=\"date\" value={date} onChange={e => setDate(e.target.value)} />",
  "          </div>",
  "          <div className=\"admin-form-row\">",
  "            <label>报名截止日期</label>",
  "            <input type=\"date\" value={deadline} onChange={e => setDeadline(e.target.value)} />",
  "          </div>",
  "          <button onClick={handleCreateMarket} style={{ alignSelf: 'flex-start' }}>创建市场</button>",
  "        </div>",
  "      </div>",
  "",
  "      <div className=\"admin-section\">",
  "        <h3>市场管理</h3>",
  "        <div className=\"admin-market-list\">",
  "          {markets.map(market => {",
  "            const booked = market.stalls.filter(s => s.booked).length;",
  "            const isExpanded = expandedMarket === market.id;",
  "            return (",
  "              <div key={market.id} className=\"admin-market-item\" style={{ flexDirection: 'column', alignItems: 'stretch' }}>",
  "                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>",
  "                  <div className=\"admin-market-info\">",
  "                    <h4>{market.name}</h4>",
  "                    <p>日期：{market.date} | 摊位：{booked}/{market.totalStalls}</p>",
  "                  </div>",
  "                  <div style={{ display: 'flex', gap: '8px' }}>",
  "                    <button onClick={() => navigate('/market/' + market.id)}>查看详情</button>",
  "                    <button onClick={() => setExpandedMarket(isExpanded ? null : market.id)} style={{ backgroundColor: '#ab47bc' }}>",
  "                      {isExpanded ? '收起' : '管理摊位'}",
  "                    </button>",
  "                  </div>",
  "                </div>",
  "                {isExpanded && (",
  "                  <div style={{ marginTop: '16px' }}>",
  "                    <p style={{ fontSize: '13px', color: '#7b1fa2', marginBottom: '8px' }}>点击摊位可手动标记预订/取消</p>",
  "                    <div className=\"admin-stalls\">",
  "                      {market.stalls.map(stall => (",
  "                        <div key={stall.id} className={'admin-stall ' + (stall.booked ? 'occupied' : 'empty')} onClick={() => handleToggleStall(market.id, stall.id, stall.booked)}>",
  "                          {stall.id}",
  "                          {stall.booked && <br />}",
  "                          {stall.booked && (stall.category ? stall.category.charAt(0) : '✓')}",
  "                        </div>",
  "                      ))}",
  "                    </div>",
  "                  </div>",
  "                )}",
  "              </div>",
  "            );",
  "          })}",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default AdminPanel;",
].join('\n');

const marketListCode = [
  "import { useState } from 'react';",
  "import { useNavigate } from 'react-router-dom';",
  "import { useApp } from '../App';",
  "import { Stall } from '../types';",
  "",
  "const MarketList = () => {",
  "  const { markets } = useApp();",
  "  const [search, setSearch] = useState('');",
  "  const navigate = useNavigate();",
  "",
  "  const filteredMarkets = markets.filter(m =>",
  "    m.name.toLowerCase().includes(search.toLowerCase())",
  "  );",
  "",
  "  const getBookedCount = (stalls: Stall[]) =>",
  "    stalls.filter(s => s.booked).length;",
  "",
  "  return (",
  "    <div className=\"market-list fade-in\">",
  "      <div className=\"search-box\">",
  "        <input",
  "          type=\"text\"",
  "          placeholder=\"搜索市场名称...\"",
  "          value={search}",
  "          onChange={e => setSearch(e.target.value)}",
  "        />",
  "      </div>",
  "      <div className=\"market-grid\">",
  "        {filteredMarkets.map(market => {",
  "          const booked = getBookedCount(market.stalls);",
  "          return (",
  "            <div",
  "              key={market.id}",
  "              className=\"market-card\"",
  "              onClick={() => navigate('/market/' + market.id)}",
  "            >",
  "              <div>",
  "                <h3>{market.name}</h3>",
  "                <div className=\"date\">活动日期：{market.date}</div>",
  "                <div className=\"stall-info\">",
  "                  {'摊位：' + booked + '/' + market.totalStalls + ' 已预订'}",
  "                </div>",
  "                <div className=\"deadline\">报名截止：{market.deadline}</div>",
  "              </div>",
  "              <button",
  "                onClick={e => {",
  "                  e.stopPropagation();",
  "                  navigate('/market/' + market.id);",
  "                }}",
  "              >",
  "                立即报名",
  "              </button>",
  "            </div>",
  "          );",
  "        })}",
  "      </div>",
  "      {filteredMarkets.length === 0 && (",
  "        <div style={{ textAlign: 'center', padding: '40px', color: '#7b1fa2' }}>",
  "          未找到匹配的市场",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "};",
  "",
  "export default MarketList;",
].join('\n');

const marketStatsCode = [
  "import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';",
  "import { Market, Category } from '../types';",
  "",
  "interface CategoryDataItem {",
  "  name: string;",
  "  value: number;",
  "}",
  "",
  "interface MarketStatsProps {",
  "  market: Market;",
  "}",
  "",
  "const COLORS = ['#ec407a', '#ab47bc', '#7e57c2', '#5c6bc0', '#42a5f5', '#26c6da'];",
  "",
  "const MarketStats = ({ market }: MarketStatsProps) => {",
  "  const totalStalls = market.totalStalls;",
  "  const bookedStalls = market.stalls.filter(s => s.booked).length;",
  "  const estimatedRevenue = bookedStalls * 100;",
  "",
  "  const categoryData: CategoryDataItem[] = market.stalls",
  "    .filter(s => s.booked && s.category)",
  "    .reduce((acc: CategoryDataItem[], stall) => {",
  "      const cat = stall.category as Category;",
  "      const existing = acc.find(item => item.name === cat);",
  "      if (existing) {",
  "        existing.value++;",
  "      } else {",
  "        acc.push({ name: cat, value: 1 });",
  "      }",
  "      return acc;",
  "    }, []);",
  "",
  "  if (categoryData.length === 0) {",
  "    categoryData.push({ name: '暂无数据', value: 1 });",
  "  }",
  "",
  "  const ratingCounts = [1, 2, 3, 4, 5].map(rating => ({",
  "    rating: rating + '星',",
  "    count: market.feedbacks.filter(f => f.rating === rating).length,",
  "  }));",
  "",
  "  return (",
  "    <div className=\"market-stats fade-in\">",
  "      <h2>{market.name} - 活动统计</h2>",
  "",
  "      <div className=\"stats-cards\">",
  "        <div className=\"stat-card\">",
  "          <div className=\"label\">总摊位数</div>",
  "          <div className=\"value\">{totalStalls}</div>",
  "        </div>",
  "        <div className=\"stat-card\">",
  "          <div className=\"label\">实际入驻数</div>",
  "          <div className=\"value\">{bookedStalls}</div>",
  "        </div>",
  "        <div className=\"stat-card\">",
  "          <div className=\"label\">交易估算总额</div>",
  "          <div className=\"value\">¥{estimatedRevenue}</div>",
  "        </div>",
  "      </div>",
  "",
  "      <div className=\"charts-container\">",
  "        <div className=\"chart-wrapper\">",
  "          <h4>摊位类别分布</h4>",
  "          <ResponsiveContainer width=\"100%\" height={240}>",
  "            <PieChart>",
  "              <Pie",
  "                data={categoryData}",
  "                cx=\"50%\"",
  "                cy=\"50%\"",
  "                innerRadius={50}",
  "                outerRadius={80}",
  "                paddingAngle={2}",
  "                dataKey=\"value\"",
  "                label={({ name, percent }) => name + ' ' + Math.round(percent * 100) + '%'}",
  "              >",
  "                {categoryData.map((_, index) => (",
  "                  <Cell key={'cell-' + index} fill={COLORS[index % COLORS.length]} />",
  "                ))}",
  "              </Pie>",
  "              <Tooltip />",
  "              <Legend />",
  "            </PieChart>",
  "          </ResponsiveContainer>",
  "        </div>",
  "",
  "        <div className=\"chart-wrapper\">",
  "          <h4>评分分布</h4>",
  "          <ResponsiveContainer width=\"100%\" height={240}>",
  "            <BarChart data={ratingCounts}>",
  "              <CartesianGrid strokeDasharray=\"3 3\" stroke=\"#e0e0e0\" />",
  "              <XAxis dataKey=\"rating\" tick={{ fill: '#6a1b9a', fontSize: 12 }} />",
  "              <YAxis tick={{ fill: '#6a1b9a', fontSize: 12 }} allowDecimals={false} />",
  "              <Tooltip",
  "                contentStyle={{",
  "                  backgroundColor: 'white',",
  "                  border: '1px solid #e0e0e0',",
  "                  borderRadius: '8px',",
  "                }}",
  "              />",
  "              <Legend />",
  "              <Bar dataKey=\"count\" name=\"评价数量\" fill=\"#ec407a\" radius={[4, 4, 0, 0]} />",
  "            </BarChart>",
  "          </ResponsiveContainer>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default MarketStats;",
].join('\n');

const profileCode = [
  "import { useApp } from '../App';",
  "import { useNavigate } from 'react-router-dom';",
  "",
  "const Profile = () => {",
  "  const { user, markets } = useApp();",
  "  const navigate = useNavigate();",
  "",
  "  if (!user) {",
  "    return (",
  "      <div style={{ padding: '40px', textAlign: 'center' }} className=\"fade-in\">",
  "        <h2 style={{ color: '#4a148c', marginBottom: '16px' }}>请先登录</h2>",
  "        <p style={{ color: '#7b1fa2', marginBottom: '20px' }}>登录后可查看您的活动历史</p>",
  "        <button onClick={() => navigate('/')}>返回首页</button>",
  "      </div>",
  "    );",
  "  }",
  "",
  "  const userBookings = markets.flatMap(market =>",
  "    market.stalls",
  "      .filter(stall => stall.userId === user.id && stall.booked)",
  "      .map(stall => ({",
  "        market,",
  "        stall,",
  "        feedback: market.feedbacks.find(f => f.userId === user.id),",
  "      }))",
  "  );",
  "",
  "  const renderStars = (rating: number) => {",
  "    return '★'.repeat(rating) + '☆'.repeat(5 - rating);",
  "  };",
  "",
  "  return (",
  "    <div className=\"profile-page fade-in\">",
  "      <h2>个人中心</h2>",
  "",
  "      <div className=\"profile-section\">",
  "        <h3>用户信息</h3>",
  "        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>",
  "          <div style={{",
  "            width: '60px', height: '60px', borderRadius: '50%',",
  "            backgroundColor: '#ec407a', color: 'white',",
  "            display: 'flex', alignItems: 'center', justifyContent: 'center',",
  "            fontSize: '24px', fontWeight: 700",
  "          }}>",
  "            {user.name.charAt(0)}",
  "          </div>",
  "          <div>",
  "            <div style={{ fontSize: '18px', fontWeight: 600, color: '#4a148c' }}>{user.name}</div>",
  "            <div style={{ fontSize: '13px', color: '#7b1fa2' }}>",
  "              {(user.isAdmin ? '管理员' : '普通用户') + ' | ID: ' + user.id}",
  "            </div>",
  "          </div>",
  "        </div>",
  "      </div>",
  "",
  "      <div className=\"profile-section\">",
  "        <h3>我的活动历史</h3>",
  "        {userBookings.length === 0 ? (",
  "          <p style={{ color: '#7b1fa2', fontSize: '14px' }}>暂无参与的活动</p>",
  "        ) : (",
  "          <div className=\"history-list\">",
  "            {userBookings.map(({ market, stall, feedback }, index) => (",
  "              <div key={market.id + '-' + stall.id + '-' + index} className=\"history-item\">",
  "                <h4>{market.name}</h4>",
  "                <div className=\"date\">活动日期：{market.date}</div>",
  "                <div className=\"stall-info\">",
  "                  {'摊位号：#' + stall.id + ' | 类别：' + stall.category}",
  "                </div>",
  "                {stall.description && (",
  "                  <div style={{ fontSize: '13px', color: '#6a1b9a', marginBottom: '8px' }}>",
  "                    {'简介：' + stall.description}",
  "                  </div>",
  "                )}",
  "                {feedback ? (",
  "                  <div className=\"feedback-display\">",
  "                    <div className=\"rating\" style={{ fontSize: '16px' }}>",
  "                      {renderStars(feedback.rating)}",
  "                    </div>",
  "                    <div className=\"comment\">{feedback.comment}</div>",
  "                    <div style={{ fontSize: '11px', color: '#8e24aa', marginTop: '4px' }}>",
  "                      {feedback.createdAt}",
  "                    </div>",
  "                  </div>",
  "                ) : (",
  "                  <button onClick={() => navigate('/market/' + market.id)} style={{ marginTop: '8px' }}>",
  "                    去评价",
  "                  </button>",
  "                )}",
  "              </div>",
  "            ))}",
  "          </div>",
  "        )}",
  "      </div>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default Profile;",
].join('\n');

fs.writeFileSync(path.join('src', 'client', 'components', 'AdminPanel.tsx'), adminPanelCode, 'utf8');
console.log('AdminPanel.tsx written');

fs.writeFileSync(path.join('src', 'client', 'components', 'MarketList.tsx'), marketListCode, 'utf8');
console.log('MarketList.tsx written');

fs.writeFileSync(path.join('src', 'client', 'components', 'MarketStats.tsx'), marketStatsCode, 'utf8');
console.log('MarketStats.tsx written');

fs.writeFileSync(path.join('src', 'client', 'components', 'Profile.tsx'), profileCode, 'utf8');
console.log('Profile.tsx written');
