const fs = require('fs');
const path = require('path');

const marketStatsCode = [
  "import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';",
  "import { Market } from '../types';",
  "",
  "interface MarketStatsProps {",
  "  market: Market;",
  "}",
  "",
  "const COLORS = ['#ec407a', '#ab47bc', '#7e57c2', '#5c6bc0', '#42a5f5', '#26c6da'];",
  "",
  "const MarketStats = ({ market }: MarketStatsProps) => {",
  "  const totalStalls = market.totalStalls;",
  "  const bookedStalls = market.stalls.filter(s => s.booked).length;",
  "  const estimatedRevenue = bookedStalls * 100;",
  "",
  "  const categoryData = market.stalls",
  "    .filter(s => s.booked && s.category)",
  "    .reduce((acc, stall) => {",
  "      const existing = acc.find(item => item.name === stall.category);",
  "      if (existing) {",
  "        existing.value++;",
  "      } else {",
  "        acc.push({ name: stall.category, value: 1 });",
  "      }",
  "      return acc;",
  "    }, []);",
  "",
  "  if (categoryData.length === 0) {",
  "    categoryData.push({ name: '暂无数据', value: 1 });",
  "  }",
  "",
  "  const ratingCounts = [1, 2, 3, 4, 5].map(rating => ({",
  "    rating: rating + '星',",
  "    count: market.feedbacks.filter(f => f.rating === rating).length,",
  "  }));",
  "",
  "  return (",
  "    <div className=\"market-stats fade-in\">",
  "      <h2>{market.name} - 活动统计</h2>",
  "",
  "      <div className=\"stats-cards\">",
  "        <div className=\"stat-card\">",
  "          <div className=\"label\">总摊位数</div>",
  "          <div className=\"value\">{totalStalls}</div>",
  "        </div>",
  "        <div className=\"stat-card\">",
  "          <div className=\"label\">实际入驻数</div>",
  "          <div className=\"value\">{bookedStalls}</div>",
  "        </div>",
  "        <div className=\"stat-card\">",
  "          <div className=\"label\">交易估算总额</div>",
  "          <div className=\"value\">¥{estimatedRevenue}</div>",
  "        </div>",
  "      </div>",
  "",
  "      <div className=\"charts-container\">",
  "        <div className=\"chart-wrapper\">",
  "          <h4>摊位类别分布</h4>",
  "          <ResponsiveContainer width=\"100%\" height={240}>",
  "            <PieChart>",
  "              <Pie",
  "                data={categoryData}",
  "                cx=\"50%\"",
  "                cy=\"50%\"",
  "                innerRadius={50}",
  "                outerRadius={80}",
  "                paddingAngle={2}",
  "                dataKey=\"value\"",
  "                label={({ name, percent }) => name + ' ' + Math.round(percent * 100) + '%'}",
  "              >",
  "                {categoryData.map((_, index) => (",
  "                  <Cell key={'cell-' + index} fill={COLORS[index % COLORS.length]} />",
  "                ))}",
  "              </Pie>",
  "              <Tooltip />",
  "              <Legend />",
  "            </PieChart>",
  "          </ResponsiveContainer>",
  "        </div>",
  "",
  "        <div className=\"chart-wrapper\">",
  "          <h4>评分分布</h4>",
  "          <ResponsiveContainer width=\"100%\" height={240}>",
  "            <BarChart data={ratingCounts}>",
  "              <CartesianGrid strokeDasharray=\"3 3\" stroke=\"#e0e0e0\" />",
  "              <XAxis dataKey=\"rating\" tick={{ fill: '#6a1b9a', fontSize: 12 }} />",
  "              <YAxis tick={{ fill: '#6a1b9a', fontSize: 12 }} allowDecimals={false} />",
  "              <Tooltip",
  "                contentStyle={{",
  "                  backgroundColor: 'white',",
  "                  border: '1px solid #e0e0e0',",
  "                  borderRadius: '8px',",
  "                }}",
  "              />",
  "              <Legend />",
  "              <Bar dataKey=\"count\" name=\"评价数量\" fill=\"#ec407a\" radius={[4, 4, 0, 0]} />",
  "            </BarChart>",
  "          </ResponsiveContainer>",
  "        </div>",
  "      </div>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default MarketStats;",
].join('\n');

const profileCode = [
  "import { useApp } from '../App';",
  "import { useNavigate } from 'react-router-dom';",
  "",
  "const Profile = () => {",
  "  const { user, markets } = useApp();",
  "  const navigate = useNavigate();",
  "",
  "  if (!user) {",
  "    return (",
  "      <div style={{ padding: '40px', textAlign: 'center' }} className=\"fade-in\">",
  "        <h2 style={{ color: '#4a148c', marginBottom: '16px' }}>请先登录</h2>",
  "        <p style={{ color: '#7b1fa2', marginBottom: '20px' }}>登录后可查看您的活动历史</p>",
  "        <button onClick={() => navigate('/')}>返回首页</button>",
  "      </div>",
  "    );",
  "  }",
  "",
  "  const userBookings = markets.flatMap(market =>",
  "    market.stalls",
  "      .filter(stall => stall.userId === user.id && stall.booked)",
  "      .map(stall => ({",
  "        market,",
  "        stall,",
  "        feedback: market.feedbacks.find(f => f.userId === user.id),",
  "      }))",
  "  );",
  "",
  "  const renderStars = (rating) => {",
  "    return '★'.repeat(rating) + '☆'.repeat(5 - rating);",
  "  };",
  "",
  "  return (",
  "    <div className=\"profile-page fade-in\">",
  "      <h2>个人中心</h2>",
  "",
  "      <div className=\"profile-section\">",
  "        <h3>用户信息</h3>",
  "        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>",
  "          <div style={{",
  "            width: '60px', height: '60px', borderRadius: '50%',",
  "            backgroundColor: '#ec407a', color: 'white',",
  "            display: 'flex', alignItems: 'center', justifyContent: 'center',",
  "            fontSize: '24px', fontWeight: 700",
  "          }}>",
  "            {user.name.charAt(0)}",
  "          </div>",
  "          <div>",
  "            <div style={{ fontSize: '18px', fontWeight: 600, color: '#4a148c' }}>{user.name}</div>",
  "            <div style={{ fontSize: '13px', color: '#7b1fa2' }}>",
  "              {(user.isAdmin ? '管理员' : '普通用户') + ' | ID: ' + user.id}",
  "            </div>",
  "          </div>",
  "        </div>",
  "      </div>",
  "",
  "      <div className=\"profile-section\">",
  "        <h3>我的活动历史</h3>",
  "        {userBookings.length === 0 ? (",
  "          <p style={{ color: '#7b1fa2', fontSize: '14px' }}>暂无参与的活动</p>",
  "        ) : (",
  "          <div className=\"history-list\">",
  "            {userBookings.map(({ market, stall, feedback }, index) => (",
  "              <div key={market.id + '-' + stall.id + '-' + index} className=\"history-item\">",
  "                <h4>{market.name}</h4>",
  "                <div className=\"date\">活动日期：{market.date}</div>",
  "                <div className=\"stall-info\">",
  "                  {'摊位号：#' + stall.id + ' | 类别：' + stall.category}",
  "                </div>",
  "                {stall.description && (",
  "                  <div style={{ fontSize: '13px', color: '#6a1b9a', marginBottom: '8px' }}>",
  "                    {'简介：' + stall.description}",
  "                  </div>",
  "                )}",
  "                {feedback ? (",
  "                  <div className=\"feedback-display\">",
  "                    <div className=\"rating\" style={{ fontSize: '16px' }}>",
  "                      {renderStars(feedback.rating)}",
  "                    </div>",
  "                    <div className=\"comment\">{feedback.comment}</div>",
  "                    <div style={{ fontSize: '11px', color: '#8e24aa', marginTop: '4px' }}>",
  "                      {feedback.createdAt}",
  "                    </div>",
  "                  </div>",
  "                ) : (",
  "                  <button onClick={() => navigate('/market/' + market.id)} style={{ marginTop: '8px' }}>",
  "                    去评价",
  "                  </button>",
  "                )}",
  "              </div>",
  "            ))}",
  "          </div>",
  "        )}",
  "      </div>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default Profile;",
].join('\n');

const appCode = [
  "import { useState, createContext, useContext } from 'react';",
  "import { Routes, Route, Link, useLocation, useNavigate } from 'react-router-dom';",
  "import { v4 as uuidv4 } from 'uuid';",
  "import MarketList from './components/MarketList';",
  "import StallGrid from './components/StallGrid';",
  "import AdminPanel from './components/AdminPanel';",
  "import Profile from './components/Profile';",
  "import { Market, User, ToastItem, Stall, Feedback, Category } from './types';",
  "",
  "interface AppContextType {",
  "  user: User | null;",
  "  setUser: (user: User | null) => void;",
  "  markets: Market[];",
  "  setMarkets: (markets: Market[]) => void;",
  "  addToast: (type: 'success' | 'error', message: string) => void;",
  "  bookStall: (marketId: string, stallId: number, category: Category, description: string, contact: string) => void;",
  "  cancelStall: (marketId: string, stallId: number) => void;",
  "  addMarket: (name: string, date: string, deadline: string) => void;",
  "  addFeedback: (marketId: string, rating: number, comment: string) => void;",
  "}",
  "",
  "const AppContext = createContext<AppContextType | null>(null);",
  "",
  "export const useApp = () => {",
  "  const context = useContext(AppContext);",
  "  if (!context) throw new Error('useApp must be used within AppProvider');",
  "  return context;",
  "};",
  "",
  "const createInitialStalls = (): Stall[] => {",
  "  return Array.from({ length: 16 }, (_, i) => ({",
  "    id: i + 1,",
  "    booked: false,",
  "  }));",
  "};",
  "",
  "const createInitialMarkets = (): Market[] => [",
  "  {",
  "    id: '1',",
  "    name: '春日跳蚤市场',",
  "    date: '2026-07-15',",
  "    deadline: '2026-07-10',",
  "    totalStalls: 16,",
  "    stalls: [",
  "      ...createInitialStalls().slice(0, 3).map(s => ({",
  "        ...s,",
  "        booked: true,",
  "        category: '二手书籍' as Category,",
  "        description: '各类小说和教材',",
  "        contact: '13800138001',",
  "        userId: 'user1',",
  "        userName: '张三',",
  "      })),",
  "      ...createInitialStalls().slice(3, 5).map(s => ({",
  "        ...s,",
  "        booked: true,",
  "        category: '手工艺品' as Category,",
  "        description: '手工编织品',",
  "        contact: '13800138002',",
  "        userId: 'user2',",
  "        userName: '李四',",
  "      })),",
  "      ...createInitialStalls().slice(5),",
  "    ],",
  "    feedbacks: [",
  "      { id: 'f1', marketId: '1', userId: 'user1', userName: '张三', rating: 5, comment: '活动很棒，人流量大！', createdAt: '2026-06-20' },",
  "      { id: 'f2', marketId: '1', userId: 'user2', userName: '李四', rating: 4, comment: '组织得不错，下次还来', createdAt: '2026-06-21' },",
  "    ],",
  "  },",
  "  {",
  "    id: '2',",
  "    name: '夏日清凉市集',",
  "    date: '2026-08-05',",
  "    deadline: '2026-07-30',",
  "    totalStalls: 16,",
  "    stalls: [",
  "      ...createInitialStalls().slice(0, 2).map(s => ({",
  "        ...s,",
  "        booked: true,",
  "        category: '家居用品' as Category,",
  "        description: '小家电和日用品',",
  "        contact: '13800138003',",
  "        userId: 'user3',",
  "        userName: '王五',",
  "      })),",
  "      ...createInitialStalls().slice(2),",
  "    ],",
  "    feedbacks: [],",
  "  },",
  "  {",
  "    id: '3',",
  "    name: '周末二手交易',",
  "    date: '2026-06-28',",
  "    deadline: '2026-06-26',",
  "    totalStalls: 16,",
  "    stalls: createInitialStalls(),",
  "    feedbacks: [],",
  "  },",
  "];",
  "",
  "const ToastContainer = ({ toasts }: { toasts: ToastItem[] }) => (",
  "  <div className=\"toast-container\">",
  "    {toasts.map(toast => (",
  "      <div key={toast.id} className={'toast ' + toast.type}>",
  "        {toast.message}",
  "      </div>",
  "    ))}",
  "  </div>",
  ");",
  "",
  "const Navbar = () => {",
  "  const location = useLocation();",
  "  const { user, setUser } = useApp();",
  "  const navigate = useNavigate();",
  "",
  "  const handleLogin = () => {",
  "    setUser({ id: 'user1', name: '测试用户', isAdmin: true });",
  "  };",
  "",
  "  const handleLogout = () => {",
  "    setUser(null);",
  "    navigate('/');",
  "  };",
  "",
  "  return (",
  "    <nav className=\"navbar\">",
  "      <div className=\"navbar-brand\">跳蚤市场管理系统</div>",
  "      <div className=\"navbar-links\">",
  "        <Link to=\"/\" className={location.pathname === '/' ? 'active' : ''}>市场列表</Link>",
  "        <Link to=\"/admin\" className={location.pathname === '/admin' ? 'active' : ''}>管理员后台</Link>",
  "        <Link to=\"/profile\" className={location.pathname === '/profile' ? 'active' : ''}>个人中心</Link>",
  "        {user ? (",
  "          <button onClick={handleLogout} style={{ padding: '6px 12px', fontSize: '12px' }}>",
  "            {'退出 (' + user.name + ')'}",
  "          </button>",
  "        ) : (",
  "          <button onClick={handleLogin} style={{ padding: '6px 12px', fontSize: '12px' }}>",
  "            登录",
  "          </button>",
  "        )}",
  "      </div>",
  "    </nav>",
  "  );",
  "};",
  "",
  "const MarketDetail = () => {",
  "  const { markets } = useApp();",
  "  const location = useLocation();",
  "  const id = location.pathname.split('/')[2];",
  "  const market = markets.find(m => m.id === id);",
  "",
  "  if (!market) {",
  "    return <div style={{ padding: '24px' }}>市场不存在</div>;",
  "  }",
  "",
  "  return (",
  "    <div className=\"market-detail fade-in\">",
  "      <div className=\"market-detail-header\">",
  "        <h2>{market.name}</h2>",
  "        <p style={{ color: '#7b1fa2', fontSize: '14px' }}>",
  "          {'活动日期：' + market.date + ' | 报名截止：' + market.deadline}",
  "        </p>",
  "      </div>",
  "      <StallGrid market={market} />",
  "    </div>",
  "  );",
  "};",
  "",
  "function App() {",
  "  const [user, setUser] = useState<User | null>(null);",
  "  const [markets, setMarkets] = useState<Market[]>(createInitialMarkets());",
  "  const [toasts, setToasts] = useState<ToastItem[]>([]);",
  "",
  "  const addToast = (type: 'success' | 'error', message: string) => {",
  "    const id = uuidv4();",
  "    setToasts(prev => [...prev, { id, type, message }]);",
  "    setTimeout(() => {",
  "      setToasts(prev => prev.filter(t => t.id !== id));",
  "    }, 3000);",
  "  };",
  "",
  "  const bookStall = (marketId: string, stallId: number, category: Category, description: string, contact: string) => {",
  "    if (!user) {",
  "      addToast('error', '请先登录');",
  "      return;",
  "    }",
  "    setMarkets(prev => prev.map(market => {",
  "      if (market.id !== marketId) return market;",
  "      return {",
  "        ...market,",
  "        stalls: market.stalls.map(stall => {",
  "          if (stall.id !== stallId || stall.booked) return stall;",
  "          return {",
  "            ...stall,",
  "            booked: true,",
  "            category,",
  "            description,",
  "            contact,",
  "            userId: user.id,",
  "            userName: user.name,",
  "          };",
  "        }),",
  "      };",
  "    }));",
  "    addToast('success', '摊位预订成功！');",
  "  };",
  "",
  "  const cancelStall = (marketId: string, stallId: number) => {",
  "    setMarkets(prev => prev.map(market => {",
  "      if (market.id !== marketId) return market;",
  "      return {",
  "        ...market,",
  "        stalls: market.stalls.map(stall => {",
  "          if (stall.id !== stallId) return stall;",
  "          return { id: stall.id, booked: false };",
  "        }),",
  "      };",
  "    }));",
  "    addToast('success', '摊位已取消');",
  "  };",
  "",
  "  const addMarket = (name: string, date: string, deadline: string) => {",
  "    const newMarket: Market = {",
  "      id: uuidv4(),",
  "      name,",
  "      date,",
  "      deadline,",
  "      totalStalls: 16,",
  "      stalls: createInitialStalls(),",
  "      feedbacks: [],",
  "    };",
  "    setMarkets(prev => [...prev, newMarket]);",
  "    addToast('success', '市场创建成功！');",
  "  };",
  "",
  "  const addFeedback = (marketId: string, rating: number, comment: string) => {",
  "    if (!user) {",
  "      addToast('error', '请先登录');",
  "      return;",
  "    }",
  "    const feedback: Feedback = {",
  "      id: uuidv4(),",
  "      marketId,",
  "      userId: user.id,",
  "      userName: user.name,",
  "      rating,",
  "      comment,",
  "      createdAt: new Date().toISOString().split('T')[0],",
  "    };",
  "    setMarkets(prev => prev.map(market => {",
  "      if (market.id !== marketId) return market;",
  "      return { ...market, feedbacks: [...market.feedbacks, feedback] };",
  "    }));",
  "    addToast('success', '评价提交成功！');",
  "  };",
  "",
  "  const contextValue: AppContextType = {",
  "    user,",
  "    setUser,",
  "    markets,",
  "    setMarkets,",
  "    addToast,",
  "    bookStall,",
  "    cancelStall,",
  "    addMarket,",
  "    addFeedback,",
  "  };",
  "",
  "  return (",
  "    <AppContext.Provider value={contextValue}>",
  "      <div style={{ minHeight: '100vh' }}>",
  "        <Navbar />",
  "        <ToastContainer toasts={toasts} />",
  "        <Routes>",
  "          <Route path=\"/\" element={<MarketList />} />",
  "          <Route path=\"/market/:id\" element={<MarketDetail />} />",
  "          <Route path=\"/admin\" element={<AdminPanel />} />",
  "          <Route path=\"/profile\" element={<Profile />} />",
  "        </Routes>",
  "      </div>",
  "    </AppContext.Provider>",
  "  );",
  "}",
  "",
  "export default App;",
].join('\n');

const stallGridCode = [
  "import { useState } from 'react';",
  "import { useApp } from '../App';",
  "import { Market, Category } from '../types';",
  "import FeedbackForm from './FeedbackForm';",
  "import MarketStats from './MarketStats';",
  "",
  "interface StallGridProps {",
  "  market: Market;",
  "}",
  "",
  "const StallGrid = ({ market }: StallGridProps) => {",
  "  const { bookStall, user } = useApp();",
  "  const [selectedStall, setSelectedStall] = useState<number | null>(null);",
  "  const [category, setCategory] = useState<Category>('二手书籍');",
  "  const [description, setDescription] = useState('');",
  "  const [contact, setContact] = useState('');",
  "  const [showStats, setShowStats] = useState(false);",
  "",
  "  const categories: Category[] = ['二手书籍', '手工艺品', '家居用品', '电子设备', '服饰配饰', '其他'];",
  "",
  "  const handleStallClick = (stallId: number) => {",
  "    const stall = market.stalls.find(s => s.id === stallId);",
  "    if (stall && !stall.booked) {",
  "      setSelectedStall(stallId);",
  "    }",
  "  };",
  "",
  "  const handleSubmit = () => {",
  "    if (selectedStall === null) return;",
  "    if (!description.trim()) {",
  "      alert('请填写商品简介');",
  "      return;",
  "    }",
  "    if (!contact.trim()) {",
  "      alert('请填写联系方式');",
  "      return;",
  "    }",
  "    bookStall(market.id, selectedStall, category, description, contact);",
  "    closeModal();",
  "  };",
  "",
  "  const closeModal = () => {",
  "    setSelectedStall(null);",
  "    setCategory('二手书籍');",
  "    setDescription('');",
  "    setContact('');",
  "  };",
  "",
  "  const getInitials = (name: string) => {",
  "    return name ? name.charAt(0) : '?';",
  "  };",
  "",
  "  return (",
  "    <div className={selectedStall !== null ? 'blur-bg' : ''}>",
  "      <div style={{ display: 'flex', gap: '12px', marginBottom: '16px', flexWrap: 'wrap' }}>",
  "        <button onClick={() => setShowStats(!showStats)}>",
  "          {showStats ? '返回摊位图' : '查看统计数据'}",
  "        </button>",
  "      </div>",
  "",
  "      {showStats ? (",
  "        <MarketStats market={market} />",
  "      ) : (",
  "        <>",
  "          <div className=\"stall-grid\">",
  "            {market.stalls.map(stall => (",
  "              <div",
  "                key={stall.id}",
  "                className={'stall-cell ' + (stall.booked ? 'occupied' : 'empty')}",
  "                onClick={() => handleStallClick(stall.id)}",
  "              >",
  "                {stall.booked ? (",
  "                  <>",
  "                    <div className=\"avatar\">{getInitials(stall.userName || '')}</div>",
  "                    {stall.category && <span className=\"category-tag\">{stall.category}</span>}",
  "                  </>",
  "                ) : (",
  "                  <span>{stall.id}</span>",
  "                )}",
  "              </div>",
  "            ))}",
  "          </div>",
  "",
  "          <div style={{ display: 'flex', gap: '16px', justifyContent: 'center', marginBottom: '24px', flexWrap: 'wrap' }}>",
  "            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>",
  "              <div style={{ width: '20px', height: '20px', backgroundColor: '#e0e0e0', borderRadius: '4px' }}></div>",
  "              <span style={{ fontSize: '13px', color: '#6a1b9a' }}>空置摊位</span>",
  "            </div>",
  "            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>",
  "              <div style={{ width: '20px', height: '20px', backgroundColor: '#ce93d8', borderRadius: '4px' }}></div>",
  "              <span style={{ fontSize: '13px', color: '#6a1b9a' }}>已预订</span>",
  "            </div>",
  "          </div>",
  "",
  "          {user && <FeedbackForm marketId={market.id} />}",
  "        </>",
  "      )}",
  "",
  "      {selectedStall !== null && (",
  "        <div className=\"modal-overlay\" onClick={e => e.target === e.currentTarget && closeModal()}>",
  "          <div className=\"modal-content\" onClick={e => e.stopPropagation()}>",
  "            <h3>{'预订摊位 #' + selectedStall}</h3>",
  "",
  "            <div>",
  "              <label>商品类别</label>",
  "              <select value={category} onChange={e => setCategory(e.target.value as Category)}>",
  "                {categories.map(c => (",
  "                  <option key={c} value={c}>{c}</option>",
  "                ))}",
  "              </select>",
  "            </div>",
  "",
  "            <div>",
  "              <label>商品简介（最多200字）</label>",
  "              <textarea",
  "                value={description}",
  "                onChange={e => setDescription(e.target.value.slice(0, 200))}",
  "                placeholder=\"请简要描述您的商品...\"",
  "                maxLength={200}",
  "              />",
  "              <div style={{ fontSize: '12px', color: '#9e9e9e', textAlign: 'right' }}>",
  "                {description.length + '/200'}",
  "              </div>",
  "            </div>",
  "",
  "            <div>",
  "              <label>联系方式</label>",
  "              <input",
  "                type=\"text\"",
  "                value={contact}",
  "                onChange={e => setContact(e.target.value)}",
  "                placeholder=\"请输入手机号或微信号\"",
  "              />",
  "            </div>",
  "",
  "            <div className=\"modal-actions\">",
  "              <button className=\"cancel-btn\" onClick={closeModal}>取消</button>",
  "              <button onClick={handleSubmit}>确认预订</button>",
  "            </div>",
  "          </div>",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "};",
  "",
  "export default StallGrid;",
].join('\n');

const marketListCode = [
  "import { useState } from 'react';",
  "import { useNavigate } from 'react-router-dom';",
  "import { useApp } from '../App';",
  "",
  "const MarketList = () => {",
  "  const { markets, user } = useApp();",
  "  const [search, setSearch] = useState('');",
  "  const navigate = useNavigate();",
  "",
  "  const filteredMarkets = markets.filter(m =>",
  "    m.name.toLowerCase().includes(search.toLowerCase())",
  "  );",
  "",
  "  const getBookedCount = (stalls) =>",
  "    stalls.filter(s => s.booked).length;",
  "",
  "  return (",
  "    <div className=\"market-list fade-in\">",
  "      <div className=\"search-box\">",
  "        <input",
  "          type=\"text\"",
  "          placeholder=\"搜索市场名称...\"",
  "          value={search}",
  "          onChange={e => setSearch(e.target.value)}",
  "        />",
  "      </div>",
  "      <div className=\"market-grid\">",
  "        {filteredMarkets.map(market => {",
  "          const booked = getBookedCount(market.stalls);",
  "          return (",
  "            <div",
  "              key={market.id}",
  "              className=\"market-card\"",
  "              onClick={() => navigate('/market/' + market.id)}",
  "            >",
  "              <div>",
  "                <h3>{market.name}</h3>",
  "                <div className=\"date\">活动日期：{market.date}</div>",
  "                <div className=\"stall-info\">",
  "                  {'摊位：' + booked + '/' + market.totalStalls + ' 已预订'}",
  "                </div>",
  "                <div className=\"deadline\">报名截止：{market.deadline}</div>",
  "              </div>",
  "              <button",
  "                onClick={e => {",
  "                  e.stopPropagation();",
  "                  navigate('/market/' + market.id);",
  "                }}",
  "              >",
  "                立即报名",
  "              </button>",
  "            </div>",
  "          );",
  "        })}",
  "      </div>",
  "      {filteredMarkets.length === 0 && (",
  "        <div style={{ textAlign: 'center', padding: '40px', color: '#7b1fa2' }}>",
  "          未找到匹配的市场",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "};",
  "",
  "export default MarketList;",
].join('\n');

const feedbackFormCode = [
  "import { useState } from 'react';",
  "import { useApp } from '../App';",
  "",
  "interface FeedbackFormProps {",
  "  marketId: string;",
  "}",
  "",
  "const FeedbackForm = ({ marketId }: FeedbackFormProps) => {",
  "  const { addFeedback } = useApp();",
  "  const [rating, setRating] = useState(0);",
  "  const [hoverRating, setHoverRating] = useState(0);",
  "  const [comment, setComment] = useState('');",
  "  const [loading, setLoading] = useState(false);",
  "",
  "  const handleSubmit = async () => {",
  "    if (rating === 0) {",
  "      alert('请选择评分');",
  "      return;",
  "    }",
  "    if (!comment.trim()) {",
  "      alert('请填写评论');",
  "      return;",
  "    }",
  "    setLoading(true);",
  "    setTimeout(() => {",
  "      addFeedback(marketId, rating, comment);",
  "      setRating(0);",
  "      setComment('');",
  "      setLoading(false);",
  "    }, 1000);",
  "  };",
  "",
  "  return (",
  "    <div className=\"feedback-form fade-in\">",
  "      <h3>提交活动评价</h3>",
  "",
  "      <div>",
  "        <label style={{ fontSize: '14px', color: '#6a1b9a', fontWeight: 500, marginBottom: '8px', display: 'block' }}>",
  "          评分",
  "        </label>",
  "        <div className=\"rating-stars\">",
  "          {[1, 2, 3, 4, 5].map(star => (",
  "            <span",
  "              key={star}",
  "              className={'star ' + (((hoverRating || rating) >= star) ? 'active' : '')}",
  "              onClick={() => !loading && setRating(star)}",
  "              onMouseEnter={() => !loading && setHoverRating(star)}",
  "              onMouseLeave={() => !loading && setHoverRating(0)}",
  "            >",
  "              ★",
  "            </span>",
  "          ))}",
  "        </div>",
  "      </div>",
  "",
  "      <div>",
  "        <label style={{ fontSize: '14px', color: '#6a1b9a', fontWeight: 500, marginBottom: '8px', display: 'block' }}>",
  "          评论",
  "        </label>",
  "        <textarea",
  "          value={comment}",
  "          onChange={e => setComment(e.target.value)}",
  "          placeholder=\"请分享您对本次活动的感受...\"",
  "          disabled={loading}",
  "        />",
  "      </div>",
  "",
  "      <button onClick={handleSubmit} disabled={loading} style={{ width: '100%' }}>",
  "        {loading ? (",
  "          <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>",
  "            <span className=\"loading-spinner\"></span>",
  "            提交中...",
  "          </span>",
  "        ) : (",
  "          '提交评价'",
  "        )}",
  "      </button>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default FeedbackForm;",
].join('\n');

const typesCode = [
  "export type Category = '二手书籍' | '手工艺品' | '家居用品' | '电子设备' | '服饰配饰' | '其他';",
  "",
  "export interface Stall {",
  "  id: number;",
  "  booked: boolean;",
  "  category?: Category;",
  "  description?: string;",
  "  contact?: string;",
  "  userId?: string;",
  "  userName?: string;",
  "}",
  "",
  "export interface Feedback {",
  "  id: string;",
  "  marketId: string;",
  "  userId: string;",
  "  userName: string;",
  "  rating: number;",
  "  comment: string;",
  "  createdAt: string;",
  "}",
  "",
  "export interface Market {",
  "  id: string;",
  "  name: string;",
  "  date: string;",
  "  deadline: string;",
  "  totalStalls: number;",
  "  stalls: Stall[];",
  "  feedbacks: Feedback[];",
  "}",
  "",
  "export interface User {",
  "  id: string;",
  "  name: string;",
  "  isAdmin: boolean;",
  "}",
  "",
  "export interface ToastItem {",
  "  id: string;",
  "  type: 'success' | 'error';",
  "  message: string;",
  "}",
].join('\n');

fs.writeFileSync(path.join('src', 'client', 'components', 'MarketStats.tsx'), marketStatsCode, 'utf8');
console.log('MarketStats.tsx written');

fs.writeFileSync(path.join('src', 'client', 'components', 'Profile.tsx'), profileCode, 'utf8');
console.log('Profile.tsx written');

fs.writeFileSync(path.join('src', 'client', 'App.tsx'), appCode, 'utf8');
console.log('App.tsx written');

fs.writeFileSync(path.join('src', 'client', 'components', 'StallGrid.tsx'), stallGridCode, 'utf8');
console.log('StallGrid.tsx written');

fs.writeFileSync(path.join('src', 'client', 'components', 'MarketList.tsx'), marketListCode, 'utf8');
console.log('MarketList.tsx written');

fs.writeFileSync(path.join('src', 'client', 'components', 'FeedbackForm.tsx'), feedbackFormCode, 'utf8');
console.log('FeedbackForm.tsx written');

fs.writeFileSync(path.join('src', 'client', 'types.ts'), typesCode, 'utf8');
console.log('types.ts written');
