import type { Question } from '../../shared/types.js';

const quizData: Question[] = [
  {
    id: 'e1',
    text: '法国的首都是哪座城市？',
    options: ['伦敦', '巴黎', '柏林', '马德里'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'e2',
    text: '晴天时天空是什么颜色？',
    options: ['红色', '绿色', '蓝色', '黄色'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'e3',
    text: '2 + 2 等于多少？',
    options: ['3', '4', '5', '6'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'e4',
    text: '一星期有几天？',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'e5',
    text: '蜜蜂生产什么？',
    options: ['牛奶', '蜂蜜', '丝绸', '黄油'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'e6',
    text: '水的化学式是什么？',
    options: ['CO2', 'H2O', 'O2', 'NaCl'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'e7',
    text: '春天之后是什么季节？',
    options: ['冬天', '秋天', '夏天', '春天'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'e8',
    text: '地球上最大的海洋是哪个？',
    options: ['大西洋', '印度洋', '北冰洋', '太平洋'],
    correctIndex: 3,
    difficulty: 'easy',
  },
  {
    id: 'e9',
    text: '离太阳最近的行星是哪颗？',
    options: ['金星', '水星', '地球', '火星'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'e10',
    text: '猫有几条腿？',
    options: ['2', '3', '4', '6'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'm1',
    text: '谁画了《蒙娜丽莎》？',
    options: ['毕加索', '梵高', '达芬奇', '米开朗基罗'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'm2',
    text: '最小的质数是多少？',
    options: ['0', '1', '2', '3'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'm3',
    text: '原子序数为1的元素是什么？',
    options: ['氦', '氢', '锂', '碳'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'm4',
    text: '第二次世界大战在哪一年结束？',
    options: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'm5',
    text: '澳大利亚的首都是哪座城市？',
    options: ['悉尼', '墨尔本', '堪培拉', '布里斯班'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'm6',
    text: '太阳系中最大的行星是哪颗？',
    options: ['土星', '木星', '天王星', '海王星'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'm7',
    text: '水在摄氏多少度沸腾？',
    options: ['90', '95', '100', '110'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'm8',
    text: '植物从大气中吸收什么气体？',
    options: ['氧气', '氮气', '二氧化碳', '氢气'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'm9',
    text: '谁写了《罗密欧与朱丽叶》？',
    options: ['狄更斯', '莎士比亚', '托尔斯泰', '雨果'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'm10',
    text: '光速大约是多少千米每秒？',
    options: ['150,000', '200,000', '300,000', '400,000'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'h1',
    text: '唯一能真正飞行的哺乳动物是什么？',
    options: ['飞鼠', '蝙蝠', '鼯鼠', '蜂鸟'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h2',
    text: '世界上最稀有的血型是什么？',
    options: ['O阴性', 'AB阴性', 'A阴性', 'B阴性'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h3',
    text: '世界上面积最小的国家是哪个？',
    options: ['摩纳哥', '梵蒂冈', '圣马力诺', '列支敦士登'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h4',
    text: '熔点最高的元素是什么？',
    options: ['铁', '钨', '铂', '锇'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h5',
    text: '谁证明了质数有无穷多个？',
    options: ['欧拉', '欧几里得', '高斯', '费马'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h6',
    text: '海洋中最深的地方在哪里？',
    options: ['汤加海沟', '马里亚纳海沟', '日本海沟', '菲律宾海沟'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h7',
    text: '谁发现了青霉素？',
    options: ['巴斯德', '弗莱明', '科赫', '詹纳'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h8',
    text: '在计算机中，CPU 代表什么？',
    options: ['中央处理单元', '计算机个人实用器', '中央程序实用器', '计算处理单元'],
    correctIndex: 0,
    difficulty: 'hard',
  },
  {
    id: 'h9',
    text: '谁提出了广义相对论？',
    options: ['牛顿', '爱因斯坦', '霍金', '玻尔'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'h10',
    text: '第一台电子计算机 ENIAC 诞生于哪一年？',
    options: ['1944', '1945', '1946', '1947'],
    correctIndex: 2,
    difficulty: 'hard',
  },
];

export default quizData;
