import { Recipe, Ingredient } from './types';

export const ingredients: Ingredient[] = [
  { id: 'i1', name: '鸡蛋', category: '蛋奶类' },
  { id: 'i2', name: '牛奶', category: '蛋奶类' },
  { id: 'i3', name: '黄油', category: '蛋奶类' },
  { id: 'i4', name: '奶油', category: '蛋奶类' },
  { id: 'i5', name: '猪肉', category: '肉类' },
  { id: 'i6', name: '牛肉', category: '肉类' },
  { id: 'i7', name: '鸡肉', category: '肉类' },
  { id: 'i8', name: '虾仁', category: '海鲜类' },
  { id: 'i9', name: '三文鱼', category: '海鲜类' },
  { id: 'i10', name: '米饭', category: '主食类' },
  { id: 'i11', name: '面条', category: '主食类' },
  { id: 'i12', name: '面粉', category: '主食类' },
  { id: 'i13', name: '番茄', category: '蔬菜类' },
  { id: 'i14', name: '土豆', category: '蔬菜类' },
  { id: 'i15', name: '胡萝卜', category: '蔬菜类' },
  { id: 'i16', name: '洋葱', category: '蔬菜类' },
  { id: 'i17', name: '青椒', category: '蔬菜类' },
  { id: 'i18', name: '白菜', category: '蔬菜类' },
  { id: 'i19', name: '蘑菇', category: '蔬菜类' },
  { id: 'i20', name: '大蒜', category: '调料类' },
  { id: 'i21', name: '生姜', category: '调料类' },
  { id: 'i22', name: '酱油', category: '调料类' },
  { id: 'i23', name: '盐', category: '调料类' },
  { id: 'i24', name: '糖', category: '调料类' },
  { id: 'i25', name: '巧克力', category: '甜点类' },
  { id: 'i26', name: '草莓', category: '水果类' },
  { id: 'i27', name: '芝士', category: '蛋奶类' },
  { id: 'i28', name: '豆腐', category: '豆制品' },
  { id: 'i29', name: '辣椒', category: '调料类' },
  { id: 'i30', name: '黄瓜', category: '蔬菜类' },
];

export const recipes: Recipe[] = [
  {
    id: 'r1',
    name: '番茄炒蛋',
    description: '经典家常菜，酸甜可口，简单易做',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['家常', '快手', '下饭菜'],
    cookingTime: 15,
    rating: 4.5,
    ingredients: [
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '3个' },
      { ingredientId: 'i13', ingredientName: '番茄', quantity: '2个' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '适量' },
      { ingredientId: 'i24', ingredientName: '糖', quantity: '1勺' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '2瓣' },
    ],
    steps: [
      '番茄切块，鸡蛋打散备用',
      '热锅下油，倒入蛋液炒至凝固盛出',
      '锅中加油，放入蒜末爆香',
      '加入番茄块翻炒出汁',
      '倒入炒好的鸡蛋，加盐和糖调味',
      '翻炒均匀即可出锅',
    ],
  },
  {
    id: 'r2',
    name: '红烧牛肉',
    description: '软烂入味的红烧牛肉，配饭神器',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['硬菜', '下饭', '宴客'],
    cookingTime: 90,
    rating: 4.8,
    ingredients: [
      { ingredientId: 'i6', ingredientName: '牛肉', quantity: '500g' },
      { ingredientId: 'i15', ingredientName: '胡萝卜', quantity: '1根' },
      { ingredientId: 'i16', ingredientName: '洋葱', quantity: '1个' },
      { ingredientId: 'i22', ingredientName: '酱油', quantity: '3勺' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '3瓣' },
      { ingredientId: 'i21', ingredientName: '生姜', quantity: '3片' },
    ],
    steps: [
      '牛肉切块，冷水下锅焯水去血沫',
      '锅中放油，加入姜片和蒜瓣爆香',
      '放入牛肉翻炒至表面微黄',
      '加入酱油调味，加热水没过牛肉',
      '大火烧开后转小火炖60分钟',
      '加入胡萝卜和洋葱继续炖20分钟',
      '大火收汁即可',
    ],
  },
  {
    id: 'r3',
    name: '意大利面',
    description: '经典番茄牛肉酱意面，浓郁美味',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop',
    category: '西餐',
    tags: ['意式', '经典', '简餐'],
    cookingTime: 30,
    rating: 4.6,
    ingredients: [
      { ingredientId: 'i11', ingredientName: '面条', quantity: '200g' },
      { ingredientId: 'i6', ingredientName: '牛肉', quantity: '200g' },
      { ingredientId: 'i13', ingredientName: '番茄', quantity: '3个' },
      { ingredientId: 'i16', ingredientName: '洋葱', quantity: '半个' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '2瓣' },
      { ingredientId: 'i3', ingredientName: '黄油', quantity: '20g' },
    ],
    steps: [
      '意面煮至八分熟捞出备用',
      '番茄去皮切块，洋葱和大蒜切碎',
      '锅中放黄油，加入洋葱蒜末炒香',
      '加入牛肉末炒至变色',
      '加入番茄块翻炒出汁，小火煮15分钟',
      '将意面倒入酱中拌匀，撒上芝士粉',
    ],
  },
  {
    id: 'r4',
    name: '草莓蛋糕',
    description: '柔软绵密的奶油草莓蛋糕，甜蜜满满',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=400&fit=crop',
    category: '甜品',
    tags: ['蛋糕', '甜点', '下午茶'],
    cookingTime: 60,
    rating: 4.9,
    ingredients: [
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '4个' },
      { ingredientId: 'i12', ingredientName: '面粉', quantity: '100g' },
      { ingredientId: 'i4', ingredientName: '奶油', quantity: '300ml' },
      { ingredientId: 'i24', ingredientName: '糖', quantity: '80g' },
      { ingredientId: 'i26', ingredientName: '草莓', quantity: '500g' },
      { ingredientId: 'i3', ingredientName: '黄油', quantity: '30g' },
    ],
    steps: [
      '蛋黄蛋白分离，蛋白分次加糖打发',
      '蛋黄加黄油和牛奶搅匀',
      '筛入面粉翻拌均匀，与蛋白霜混合',
      '倒入模具，160度烤35分钟',
      '奶油打发，蛋糕切片',
      '一层蛋糕一层奶油和草莓组装起来',
    ],
  },
  {
    id: 'r5',
    name: '宫保鸡丁',
    description: '川菜经典，酸甜微辣，鸡肉嫩滑',
    imageUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['川菜', '经典', '下饭菜'],
    cookingTime: 25,
    rating: 4.7,
    ingredients: [
      { ingredientId: 'i7', ingredientName: '鸡肉', quantity: '300g' },
      { ingredientId: 'i17', ingredientName: '青椒', quantity: '1个' },
      { ingredientId: 'i29', ingredientName: '辣椒', quantity: '适量' },
      { ingredientId: 'i22', ingredientName: '酱油', quantity: '2勺' },
      { ingredientId: 'i24', ingredientName: '糖', quantity: '2勺' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '3瓣' },
    ],
    steps: [
      '鸡肉切丁，加酱油淀粉腌制15分钟',
      '调制宫保汁：酱油、糖、醋、淀粉加水',
      '热锅下油，爆香干辣椒和花椒',
      '放入鸡丁滑炒至变色盛出',
      '下青椒翻炒，倒入鸡丁',
      '淋入宫保汁快速翻炒均匀',
    ],
  },
  {
    id: 'r6',
    name: '三文鱼刺身',
    description: '新鲜三文鱼，入口即化',
    imageUrl: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=600&h=400&fit=crop',
    category: '日料',
    tags: ['刺身', '日式', '冷盘'],
    cookingTime: 10,
    rating: 4.6,
    ingredients: [
      { ingredientId: 'i9', ingredientName: '三文鱼', quantity: '300g' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '少许' },
      { ingredientId: 'i30', ingredientName: '黄瓜', quantity: '1根' },
    ],
    steps: [
      '三文鱼去皮去骨',
      '刀沾水将三文鱼切成均匀厚片',
      '黄瓜切丝垫在盘底',
      '三文鱼片摆放在黄瓜丝上',
      '配芥末和酱油食用',
    ],
  },
  {
    id: 'r7',
    name: '石锅拌饭',
    description: '韩式经典，蔬菜丰富，锅巴香脆',
    imageUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600&h=400&fit=crop',
    category: '韩餐',
    tags: ['韩式', '拌饭', '简餐'],
    cookingTime: 35,
    rating: 4.5,
    ingredients: [
      { ingredientId: 'i10', ingredientName: '米饭', quantity: '2碗' },
      { ingredientId: 'i7', ingredientName: '鸡肉', quantity: '150g' },
      { ingredientId: 'i15', ingredientName: '胡萝卜', quantity: '半根' },
      { ingredientId: 'i18', ingredientName: '白菜', quantity: '50g' },
      { ingredientId: 'i19', ingredientName: '蘑菇', quantity: '3个' },
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '1个' },
    ],
    steps: [
      '各种蔬菜切丝，分别焯水炒熟备用',
      '鸡肉腌制后煎熟切片',
      '石锅刷香油，放入米饭',
      '将蔬菜和鸡肉摆在米饭上',
      '中间放一个煎蛋',
      '小火加热至锅底形成锅巴',
    ],
  },
  {
    id: 'r8',
    name: '土豆炖牛肉',
    description: '家常炖菜，牛肉软烂，土豆入味',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['家常', '炖菜', '下饭菜'],
    cookingTime: 80,
    rating: 4.6,
    ingredients: [
      { ingredientId: 'i6', ingredientName: '牛肉', quantity: '400g' },
      { ingredientId: 'i14', ingredientName: '土豆', quantity: '2个' },
      { ingredientId: 'i15', ingredientName: '胡萝卜', quantity: '1根' },
      { ingredientId: 'i16', ingredientName: '洋葱', quantity: '半个' },
      { ingredientId: 'i22', ingredientName: '酱油', quantity: '3勺' },
      { ingredientId: 'i21', ingredientName: '生姜', quantity: '3片' },
    ],
    steps: [
      '牛肉切块焯水',
      '土豆胡萝卜切块',
      '锅中放油爆香姜片',
      '牛肉翻炒加酱油',
      '加热水烧开转小火炖50分钟',
      '加入土豆胡萝卜继续炖20分钟',
      '大火收汁即可',
    ],
  },
  {
    id: 'r9',
    name: '巧克力慕斯',
    description: '浓郁丝滑的巧克力慕斯，入口即化',
    imageUrl: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=600&h=400&fit=crop',
    category: '甜品',
    tags: ['巧克力', '慕斯', '下午茶'],
    cookingTime: 45,
    rating: 4.8,
    ingredients: [
      { ingredientId: 'i25', ingredientName: '巧克力', quantity: '200g' },
      { ingredientId: 'i4', ingredientName: '奶油', quantity: '200ml' },
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '2个' },
      { ingredientId: 'i24', ingredientName: '糖', quantity: '50g' },
      { ingredientId: 'i3', ingredientName: '黄油', quantity: '30g' },
    ],
    steps: [
      '巧克力加黄油隔水融化',
      '蛋黄加糖打发至颜色变浅',
      '奶油打发至六分发',
      '将巧克力液与蛋黄液混合',
      '分次加入打发好的奶油翻拌',
      '倒入杯中冷藏4小时',
    ],
  },
  {
    id: 'r10',
    name: '麻婆豆腐',
    description: '川菜经典，麻辣鲜香，下饭神器',
    imageUrl: 'https://images.unsplash.com/photo-1582450871972-ab5ca641643d?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['川菜', '豆腐', '下饭菜'],
    cookingTime: 20,
    rating: 4.7,
    ingredients: [
      { ingredientId: 'i28', ingredientName: '豆腐', quantity: '1块' },
      { ingredientId: 'i5', ingredientName: '猪肉', quantity: '100g' },
      { ingredientId: 'i29', ingredientName: '辣椒', quantity: '适量' },
      { ingredientId: 'i22', ingredientName: '酱油', quantity: '1勺' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '2瓣' },
      { ingredientId: 'i21', ingredientName: '生姜', quantity: '2片' },
    ],
    steps: [
      '豆腐切块用盐水浸泡',
      '猪肉剁碎，葱姜蒜切末',
      '锅中放油炒香肉末',
      '加豆瓣酱炒出红油',
      '加适量水烧开，放入豆腐',
      '小火煮5分钟，勾芡撒花椒粉',
    ],
  },
  {
    id: 'r11',
    name: '芝士汉堡',
    description: '美式经典，双层芝士肉饼，浓郁多汁',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop',
    category: '西餐',
    tags: ['汉堡', '美式', '快餐'],
    cookingTime: 25,
    rating: 4.4,
    ingredients: [
      { ingredientId: 'i5', ingredientName: '猪肉', quantity: '200g' },
      { ingredientId: 'i27', ingredientName: '芝士', quantity: '2片' },
      { ingredientId: 'i16', ingredientName: '洋葱', quantity: '四分之一个' },
      { ingredientId: 'i30', ingredientName: '黄瓜', quantity: '几片' },
      { ingredientId: 'i13', ingredientName: '番茄', quantity: '2片' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '适量' },
    ],
    steps: [
      '牛肉加盐胡椒调味，揉成肉饼',
      '平底锅煎肉饼至喜欢的熟度',
      '放上芝士片使其融化',
      '汉堡胚烤至微焦',
      '依次放上生菜、番茄、洋葱、酸黄瓜',
      '放上肉饼，盖上面包即可',
    ],
  },
  {
    id: 'r12',
    name: '日式天妇罗',
    description: '酥脆外衣包裹鲜嫩食材，日式经典',
    imageUrl: 'https://images.unsplash.com/photo-1615361200141-f45040f367be?w=600&h=400&fit=crop',
    category: '日料',
    tags: ['日式', '油炸', '小吃'],
    cookingTime: 30,
    rating: 4.5,
    ingredients: [
      { ingredientId: 'i8', ingredientName: '虾仁', quantity: '10只' },
      { ingredientId: 'i19', ingredientName: '蘑菇', quantity: '5个' },
      { ingredientId: 'i12', ingredientName: '面粉', quantity: '100g' },
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '1个' },
      { ingredientId: 'i2', ingredientName: '牛奶', quantity: '100ml' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '少许' },
    ],
    steps: [
      '虾仁去虾线，擦干水分',
      '天妇罗粉加冰水调成面糊',
      '食材裹上面糊',
      '油温180度放入炸制',
      '炸至金黄酥脆捞出沥油',
      '配天妇罗汁食用',
    ],
  },
  {
    id: 'r13',
    name: '韩式炸鸡',
    description: '外酥里嫩，甜辣可口，人气爆棚',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&h=400&fit=crop',
    category: '韩餐',
    tags: ['韩式', '炸鸡', '小吃'],
    cookingTime: 40,
    rating: 4.6,
    ingredients: [
      { ingredientId: 'i7', ingredientName: '鸡肉', quantity: '500g' },
      { ingredientId: 'i12', ingredientName: '面粉', quantity: '100g' },
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '1个' },
      { ingredientId: 'i24', ingredientName: '糖', quantity: '3勺' },
      { ingredientId: 'i29', ingredientName: '辣椒', quantity: '适量' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '适量' },
    ],
    steps: [
      '鸡肉切块腌制20分钟',
      '裹上蛋液和面粉',
      '油温170度炸8分钟捞出',
      '油温升高再复炸2分钟',
      '调制甜辣酱，裹在炸鸡上',
      '撒上芝麻即可',
    ],
  },
  {
    id: 'r14',
    name: '鸡蛋羹',
    description: '滑嫩如布丁的蒸蛋，老少皆宜',
    imageUrl: 'https://images.unsplash.com/photo-1482049016gy-f0a1cf25d26b?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['蒸菜', '家常', '清淡'],
    cookingTime: 15,
    rating: 4.3,
    ingredients: [
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '3个' },
      { ingredientId: 'i2', ingredientName: '牛奶', quantity: '100ml' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '少许' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '1瓣' },
      { ingredientId: 'i22', ingredientName: '酱油', quantity: '少许' },
    ],
    steps: [
      '鸡蛋打散加盐',
      '加入温水或牛奶搅匀',
      '过筛去除气泡',
      '盖上保鲜膜扎孔',
      '水开后中小火蒸12分钟',
      '淋上酱油和香油即可',
    ],
  },
  {
    id: 'r15',
    name: '凯撒沙拉',
    description: '经典西餐沙拉，清爽健康',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
    category: '西餐',
    tags: ['沙拉', '健康', '轻食'],
    cookingTime: 15,
    rating: 4.2,
    ingredients: [
      { ingredientId: 'i18', ingredientName: '白菜', quantity: '200g' },
      { ingredientId: 'i27', ingredientName: '芝士', quantity: '30g' },
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '1个' },
      { ingredientId: 'i3', ingredientName: '黄油', quantity: '20g' },
      { ingredientId: 'i16', ingredientName: '洋葱', quantity: '少许' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '少许' },
    ],
    steps: [
      '生菜洗净撕成小块',
      '面包切丁用黄油煎香',
      '制作凯撒酱：蛋黄、蒜泥、芝士、橄榄油',
      '生菜淋上凯撒酱',
      '撒上面包丁和芝士粉',
    ],
  },
  {
    id: 'r16',
    name: '提拉米苏',
    description: '意式经典甜品，咖啡香浓，层次丰富',
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&h=400&fit=crop',
    category: '甜品',
    tags: ['意式', '咖啡', '甜品'],
    cookingTime: 30,
    rating: 4.9,
    ingredients: [
      { ingredientId: 'i4', ingredientName: '奶油', quantity: '250ml' },
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '3个' },
      { ingredientId: 'i27', ingredientName: '芝士', quantity: '250g' },
      { ingredientId: 'i24', ingredientName: '糖', quantity: '60g' },
      { ingredientId: 'i3', ingredientName: '黄油', quantity: '20g' },
      { ingredientId: 'i2', ingredientName: '牛奶', quantity: '50ml' },
    ],
    steps: [
      '马斯卡彭芝士加糖搅匀',
      '蛋黄打发至颜色变浅，与芝士混合',
      '奶油打发，分次拌入',
      '手指饼干快速蘸咖啡液铺底',
      '一层奶酪糊一层饼干交替铺',
      '冷藏4小时，撒可可粉',
    ],
  },
  {
    id: 'r17',
    name: '青椒肉丝',
    description: '家常快炒菜，脆嫩鲜香',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['家常', '快手', '下饭菜'],
    cookingTime: 15,
    rating: 4.4,
    ingredients: [
      { ingredientId: 'i5', ingredientName: '猪肉', quantity: '200g' },
      { ingredientId: 'i17', ingredientName: '青椒', quantity: '2个' },
      { ingredientId: 'i22', ingredientName: '酱油', quantity: '2勺' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '适量' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '2瓣' },
    ],
    steps: [
      '猪肉切丝加酱油淀粉腌制',
      '青椒去籽切丝',
      '热锅下油滑炒肉丝至变色盛出',
      '爆香蒜末，下青椒丝翻炒',
      '倒入肉丝，加盐调味',
      '翻炒均匀出锅',
    ],
  },
  {
    id: 'r18',
    name: '蒜蓉虾仁',
    description: '鲜嫩虾仁配上浓郁蒜蓉，简单美味',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
    category: '中餐',
    tags: ['海鲜', '快手', '蒸菜'],
    cookingTime: 20,
    rating: 4.6,
    ingredients: [
      { ingredientId: 'i8', ingredientName: '虾仁', quantity: '300g' },
      { ingredientId: 'i20', ingredientName: '大蒜', quantity: '10瓣' },
      { ingredientId: 'i22', ingredientName: '酱油', quantity: '2勺' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '适量' },
      { ingredientId: 'i24', ingredientName: '糖', quantity: '半勺' },
    ],
    steps: [
      '虾仁去虾线洗净',
      '大蒜剁成蒜蓉',
      '锅中放油炒香蒜蓉至微黄',
      '加入酱油、糖、盐调成蒜蓉酱',
      '虾仁摆盘，淋上蒜蓉酱',
      '水开后大火蒸6分钟',
    ],
  },
  {
    id: 'r19',
    name: '芝士披萨',
    description: '意式经典，芝士拉丝，馅料丰富',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop',
    category: '西餐',
    tags: ['意式', '披萨', '聚餐'],
    cookingTime: 45,
    rating: 4.7,
    ingredients: [
      { ingredientId: 'i12', ingredientName: '面粉', quantity: '200g' },
      { ingredientId: 'i27', ingredientName: '芝士', quantity: '150g' },
      { ingredientId: 'i13', ingredientName: '番茄', quantity: '2个' },
      { ingredientId: 'i19', ingredientName: '蘑菇', quantity: '5个' },
      { ingredientId: 'i7', ingredientName: '鸡肉', quantity: '100g' },
      { ingredientId: 'i2', ingredientName: '牛奶', quantity: '30ml' },
    ],
    steps: [
      '面粉加酵母水揉成面团发酵',
      '面团擀成饼底，用叉子插孔',
      '涂上番茄酱，撒一层芝士',
      '铺上蘑菇片、火腿、青椒等馅料',
      '再撒满芝士',
      '200度烤15分钟',
    ],
  },
  {
    id: 'r20',
    name: '日式蛋包饭',
    description: '嫩滑蛋皮包裹番茄炒饭，造型可爱',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
    category: '日料',
    tags: ['日式', '饭类', '可爱'],
    cookingTime: 30,
    rating: 4.5,
    ingredients: [
      { ingredientId: 'i1', ingredientName: '鸡蛋', quantity: '3个' },
      { ingredientId: 'i10', ingredientName: '米饭', quantity: '2碗' },
      { ingredientId: 'i13', ingredientName: '番茄', quantity: '1个' },
      { ingredientId: 'i16', ingredientName: '洋葱', quantity: '四分之一个' },
      { ingredientId: 'i7', ingredientName: '鸡肉', quantity: '80g' },
      { ingredientId: 'i23', ingredientName: '盐', quantity: '适量' },
    ],
    steps: [
      '洋葱番茄鸡肉切丁',
      '锅中炒饭，加番茄和鸡肉炒香',
      '加入米饭翻炒调味',
      '鸡蛋打散加少许盐',
      '平底锅摊出半熟蛋皮',
      '把米饭放在蛋皮中间，包起装盘',
    ],
  },
];
