export const fossilsData = [
  {
    _id: "f1",
    name: "三叶虫",
    era: "寒武纪-二叠纪",
    latinName: "Trilobita",
    description: "三叶虫是古生代最具代表性的海洋节肢动物。其背甲呈三叶状纵向分布，身体分为头、胸、尾三部分。它们在海洋生态系统中占据重要地位长达3亿年。",
    modelType: "trilobite",
    discoveryLocation: "中国山东",
    characteristics: "三叶状背甲，分头胸尾三部分",
  },
  {
    _id: "f2",
    name: "菊石",
    era: "泥盆纪-白垩纪",
    latinName: "Ammonoidea",
    description: "菊石是一类已灭绝的头足类动物，以其精美的螺旋形外壳闻名。壳体内部由隔板分隔成多个房室，用于调节浮力。它们是中生代海洋的标志性生物。",
    modelType: "ammonite",
    discoveryLocation: "马达加斯加",
    characteristics: "螺旋形外壳，房室结构",
  },
  {
    _id: "f3",
    name: "直角石",
    era: "奥陶纪-志留纪",
    latinName: "Orthoceras",
    description: "直角石是一种具有直锥形壳体的古生代头足类动物。壳体中央有体管贯穿，用于调节气体和液体以控制浮沉。它们是奥陶纪海洋中的顶级掠食者之一。",
    modelType: "orthoceras",
    discoveryLocation: "摩洛哥",
    characteristics: "直锥形壳体，体管居中",
  },
  {
    _id: "f4",
    name: "星珊瑚",
    era: "志留纪-现代",
    latinName: "Favosites",
    description: "蜂房星珊瑚是一种已灭绝的群体珊瑚，其骨骼呈蜂窝状排列。每个珊瑚虫居住在六角形的杯状结构中，形成紧密的群体。它们是古生代礁体的重要建造者。",
    modelType: "coral",
    discoveryLocation: "瑞典哥特兰",
    characteristics: "蜂窝状群体珊瑚",
  },
  {
    _id: "f5",
    name: "蝙蝠虫",
    era: "寒武纪",
    latinName: "Drepanura",
    description: "蝙蝠虫是寒武纪晚期特有的三叶虫类群。其尾甲呈扇形展开，形态酷似蝙蝠翅膀，故得名。该属是中国寒武纪地层的重要标准化石。",
    modelType: "batbug",
    discoveryLocation: "中国山东",
    characteristics: "扇形尾甲，形似蝙蝠",
  },
  {
    _id: "f6",
    name: "舌形贝",
    era: "寒武纪-现代",
    latinName: "Lingula",
    description: "舌形贝是最著名的活化石之一，从寒武纪延续至今超过5亿年。其双壳呈舌形，靠肉茎固着在海底生活。形态几乎没有变化，是生物演化中的奇迹。",
    modelType: "lingula",
    discoveryLocation: "全球分布",
    characteristics: "舌形双壳，活化石",
  },
  {
    _id: "f7",
    name: "芦木",
    era: "石炭纪-二叠纪",
    latinName: "Calamites",
    description: "芦木是石炭纪湿地森林中的重要成员，属于楔叶纲植物。其茎干中空，节部膨大，叶片轮生排列。它们可高达数十米，构成了石炭纪沼泽森林的主体。",
    modelType: "calamites",
    discoveryLocation: "欧洲",
    characteristics: "节间中空茎干，轮生叶",
  },
  {
    _id: "f8",
    name: "鳞木",
    era: "石炭纪-二叠纪",
    latinName: "Lepidodendron",
    description: "鳞木是石炭纪最壮观的高大乔木之一，高度可达30米以上。树干表面覆盖菱形叶座，脱落后留下独特的菱形印痕。它们是形成石炭纪煤炭的重要植物。",
    modelType: "lepidodendron",
    discoveryLocation: "中国山西",
    characteristics: "高大乔木，菱形叶座",
  },
  {
    _id: "f9",
    name: "科达叶",
    era: "石炭纪-二叠纪",
    latinName: "Cordaites",
    description: "科达叶是古生代晚期重要的裸子植物类群。其叶片大型披针形，具有明显的平行脉。它们既是石炭纪森林的重要组分，也是现代针叶树的近亲祖先。",
    modelType: "cordaites",
    discoveryLocation: "北美洲",
    characteristics: "大型披针形叶，平行脉",
  },
  {
    _id: "f10",
    name: "楔叶",
    era: "石炭纪-二叠纪",
    latinName: "Sphenophyllum",
    description: "楔叶是石炭纪湿地中常见的草本楔叶植物。其叶片呈楔形，多枚轮生于纤细的茎节上。它们通常作为林下植被生长在高大鳞木和芦木的遮蔽之下。",
    modelType: "sphenophyllum",
    discoveryLocation: "中国山西",
    characteristics: "楔形叶片，轮生排列",
  },
  {
    _id: "f11",
    name: "硅化木",
    era: "三叠纪-现代",
    latinName: "Petrified Wood",
    description: "硅化木是木质组织被二氧化硅完全替代的化石。替代过程中保留了原始的细胞结构和年轮纹理，使木头的微观细节得以完美保存。它们是地质历史中火山活动的见证者。",
    modelType: "petrifiedwood",
    discoveryLocation: "美国亚利桑那",
    characteristics: "木质部硅化替代，保留年轮",
  },
  {
    _id: "f12",
    name: "猛犸象牙齿",
    era: "更新世",
    latinName: "Mammuthus",
    description: "猛犸象是更新世最具代表性的大型哺乳动物之一。其弯曲的长牙由象牙质构成，表面覆盖细密的釉质层纹。西伯利亚永久冻土层中保存了大量完整的猛犸象遗骸。",
    modelType: "mammothtusk",
    discoveryLocation: "西伯利亚",
    characteristics: "弯曲长牙，釉质层纹",
  },
];
