import { Difficulty, Style, OrigamiWork } from './types';

export const origamiWorks: OrigamiWork[] = [
  { id: 1, name: '千纸鹤', difficulty: Difficulty.EASY, style: Style.ANIMAL, steps: 8, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20crane%20white%20background%20minimal&image_size=square', primaryColor: '#ec4899' },
  { id: 2, name: '纸青蛙', difficulty: Difficulty.EASY, style: Style.ANIMAL, steps: 10, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20frog%20green%20white%20background&image_size=square', primaryColor: '#22c55e' },
  { id: 3, name: '纸船', difficulty: Difficulty.EASY, style: Style.GEOMETRIC, steps: 6, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20boat%20blue%20white%20background&image_size=square', primaryColor: '#3b82f6' },
  { id: 4, name: '玫瑰花', difficulty: Difficulty.HARD, style: Style.PLANT, steps: 25, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20rose%20red%20white%20background&image_size=square', primaryColor: '#ef4444' },
  { id: 5, name: '纸飞机', difficulty: Difficulty.EASY, style: Style.GEOMETRIC, steps: 7, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20airplane%20white%20background&image_size=square', primaryColor: '#6366f1' },
  { id: 6, name: '天鹅', difficulty: Difficulty.MEDIUM, style: Style.ANIMAL, steps: 15, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20swan%20white%20elegant%20background&image_size=square', primaryColor: '#f97316' },
  { id: 7, name: '郁金香', difficulty: Difficulty.MEDIUM, style: Style.PLANT, steps: 12, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20tulip%20yellow%20white%20background&image_size=square', primaryColor: '#eab308' },
  { id: 8, name: '恐龙', difficulty: Difficulty.HARD, style: Style.ANIMAL, steps: 30, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20dinosaur%20green%20white%20background&image_size=square', primaryColor: '#16a34a' },
  { id: 9, name: '立方体', difficulty: Difficulty.MEDIUM, style: Style.GEOMETRIC, steps: 14, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20cube%20colorful%20white%20background&image_size=square', primaryColor: '#8b5cf6' },
  { id: 10, name: '枫叶', difficulty: Difficulty.HARD, style: Style.PLANT, steps: 28, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20maple%20leaf%20red%20autumn%20white%20background&image_size=square', primaryColor: '#dc2626' },
  { id: 11, name: '蝴蝶', difficulty: Difficulty.MEDIUM, style: Style.ANIMAL, steps: 16, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20butterfly%20colorful%20white%20background&image_size=square', primaryColor: '#db2777' },
  { id: 12, name: '百合花', difficulty: Difficulty.MEDIUM, style: Style.PLANT, steps: 18, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20lily%20white%20flower%20white%20background&image_size=square', primaryColor: '#f472b6' },
  { id: 13, name: '狐狸', difficulty: Difficulty.HARD, style: Style.ANIMAL, steps: 22, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20fox%20orange%20white%20background&image_size=square', primaryColor: '#ea580c' },
  { id: 14, name: '星星', difficulty: Difficulty.EASY, style: Style.GEOMETRIC, steps: 8, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20star%20yellow%20white%20background&image_size=square', primaryColor: '#fbbf24' },
  { id: 15, name: '向日葵', difficulty: Difficulty.HARD, style: Style.PLANT, steps: 32, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20sunflower%20yellow%20white%20background&image_size=square', primaryColor: '#f59e0b' },
  { id: 16, name: '兔子', difficulty: Difficulty.MEDIUM, style: Style.ANIMAL, steps: 14, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20rabbit%20white%20cute%20white%20background&image_size=square', primaryColor: '#a78bfa' },
  { id: 17, name: '八面体', difficulty: Difficulty.HARD, style: Style.GEOMETRIC, steps: 24, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20octahedron%20geometric%20white%20background&image_size=square', primaryColor: '#0ea5e9' },
  { id: 18, name: '樱花', difficulty: Difficulty.MEDIUM, style: Style.PLANT, steps: 16, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20sakura%20cherry%20blossom%20pink%20white%20background&image_size=square', primaryColor: '#f43f5e' },
  { id: 19, name: '龙', difficulty: Difficulty.HARD, style: Style.ANIMAL, steps: 40, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20dragon%20golden%20majestic%20white%20background&image_size=square', primaryColor: '#ca8a04' },
  { id: 20, name: '心形', difficulty: Difficulty.EASY, style: Style.GEOMETRIC, steps: 9, imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=origami%20paper%20heart%20red%20love%20white%20background&image_size=square', primaryColor: '#ef4444' }
];
