import type { Contour, NestedNode } from './types'

function isInside(child: Contour, parent: Contour, padding = 4): boolean {
  return (
    child.x >= parent.x - padding &&
    child.y >= parent.y - padding &&
    child.x + child.width <= parent.x + parent.width + padding &&
    child.y + child.height <= parent.y + parent.height + padding
  )
}

export function buildNestingTree(contours: Contour[]): NestedNode[] {
  const sorted = [...contours].sort((a, b) => {
    const areaA = a.width * a.height
    const areaB = b.width * b.height
    return areaB - areaA
  })

  const assigned = new Set<string>()
  const roots: NestedNode[] = []

  function findParent(child: Contour, candidates: Contour[]): Contour | null {
    let directParent: Contour | null = null
    let smallestArea = Infinity

    for (const parent of candidates) {
      if (parent.id === child.id) continue
      if (!isInside(child, parent)) continue
      const area = parent.width * parent.height
      if (area < smallestArea) {
        smallestArea = area
        directParent = parent
      }
    }

    return directParent
  }

  function addToTree(node: NestedNode, tree: NestedNode[]): boolean {
    for (const root of tree) {
      if (isInside(node.contour, root.contour)) {
        if (addToTree(node, root.children)) {
          return true
        }
        root.children.push(node)
        node.contour.parentId = root.contour.id
        node.contour.depth = root.contour.depth + 1
        return true
      }
    }
    return false
  }

  const allNodes: Map<string, NestedNode> = new Map()
  for (const c of sorted) {
    allNodes.set(c.id, { contour: c, children: [] })
    c.parentId = null
    c.depth = 0
  }

  for (const contour of sorted) {
    if (assigned.has(contour.id)) continue

    const node = allNodes.get(contour.id)!
    const otherContours = sorted.filter(
      (c) => c.id !== contour.id && assigned.has(c.id)
    )

    const parent = findParent(contour, otherContours.map((c) => c))

    if (parent) {
      const parentNode = allNodes.get(parent.id)!
      let currentParent: NestedNode | null = parentNode
      let deepestParent: NestedNode = parentNode

      while (currentParent) {
        let foundInChild = false
        for (const child of currentParent.children) {
          if (isInside(contour, child.contour)) {
            deepestParent = child
            currentParent = child
            foundInChild = true
            break
          }
        }
        if (!foundInChild) break
      }

      deepestParent.children.push(node)
      node.contour.parentId = deepestParent.contour.id
      node.contour.depth = deepestParent.contour.depth + 1
    } else {
      if (!addToTree(node, roots)) {
        roots.push(node)
      }
    }

    assigned.add(contour.id)
  }

  function updateDepths(nodes: NestedNode[], depth: number) {
    for (const n of nodes) {
      n.contour.depth = depth
      updateDepths(n.children, depth + 1)
    }
  }
  updateDepths(roots, 0)

  return roots
}

function indent(level: number): string {
  return '  '.repeat(level)
}

function generateClassName(contour: Contour, index: number): string {
  if (contour.depth === 0) {
    return `container-${index + 1}`
  }
  const prefix = contour.depth === 1 ? 'box' : `child-${contour.depth}`
  return `${prefix}-${index + 1}`
}

function round(n: number): number {
  return Math.round(n * 10) / 10
}

interface GeneratedCode {
  html: string
  css: string
  combined: string
}

export function generateCode(contours: Contour[]): GeneratedCode {
  if (contours.length === 0) {
    return { html: '<!-- 暂无元素 -->', css: '/* 暂无样式 */', combined: '<!-- 暂无元素 -->' }
  }

  const tree = buildNestingTree(contours)

  let htmlLines: string[] = []
  let cssLines: string[] = []
  let elementIndex = 0

  cssLines.push('/* Generated by Design to Code */')
  cssLines.push('* { box-sizing: border-box; margin: 0; padding: 0; }')
  cssLines.push('')

  function generateFromNode(node: NestedNode, level: number, parentNode?: NestedNode) {
    elementIndex++
    const className = generateClassName(node.contour, elementIndex)

    const relX = parentNode
      ? round(node.contour.x - parentNode.contour.x)
      : round(node.contour.x)
    const relY = parentNode
      ? round(node.contour.y - parentNode.contour.y)
      : round(node.contour.y)

    htmlLines.push(
      `${indent(level)}<div class="${className}">`
    )

    cssLines.push(`.${className} {`)
    cssLines.push(`  position: ${parentNode ? 'absolute' : 'relative'};`)
    if (parentNode) {
      cssLines.push(`  left: ${relX}px;`)
      cssLines.push(`  top: ${relY}px;`)
    }
    cssLines.push(`  width: ${round(node.contour.width)}px;`)
    cssLines.push(`  height: ${round(node.contour.height)}px;`)
    cssLines.push(`  border: 1px dashed rgba(108, 99, 255, 0.5);`)
    cssLines.push(`  background: rgba(108, 99, 255, ${0.05 + node.contour.depth * 0.03});`)
    cssLines.push('}')
    cssLines.push('')

    if (node.children.length > 0) {
      for (const child of node.children) {
        generateFromNode(child, level + 1, node)
      }
    }

    htmlLines.push(`${indent(level)}</div>`)
  }

  htmlLines.push('<div class="design-root">')
  cssLines.push('.design-root {')
  cssLines.push('  position: relative;')
  if (contours.length > 0) {
    const maxRight = Math.max(...contours.map((c) => c.x + c.width))
    const maxBottom = Math.max(...contours.map((c) => c.y + c.height))
    cssLines.push(`  width: ${round(maxRight + 20)}px;`)
    cssLines.push(`  height: ${round(maxBottom + 20)}px;`)
  }
  cssLines.push('  margin: 20px;')
  cssLines.push('}')
  cssLines.push('')

  for (const root of tree) {
    generateFromNode(root, 1)
  }

  htmlLines.push('</div>')

  const htmlStr = htmlLines.join('\n')
  const cssStr = cssLines.join('\n')
  const combined = `${cssStr}\n\n<!-- HTML -->\n${htmlStr}`

  return { html: htmlStr, css: cssStr, combined }
}

export function highlightCode(code: string): string {
  let result = code

  result = result.replace(
    /(\/\*[\s\S]*?\*\/)/g,
    '<span class="comment">$1</span>'
  )
  result = result.replace(
    /(<!--[\s\S]*?-->)/g,
    '<span class="comment">$1</span>'
  )

  result = result.replace(
    /(&lt;\/?)([a-zA-Z0-9-]+)/g,
    (_, prefix, tag) => `${prefix}<span class="tag">${tag}</span>`
  )
  result = result.replace(
    /(&lt;[a-zA-Z0-9-]+)(\s+)([a-zA-Z-]+)(=)(&quot;)(.*?)(&quot;)/g,
    (_, openTag, space, attr, eq, q1, val, q2) =>
      `${openTag}${space}<span class="attr-name">${attr}</span>${eq}<span class="attr-value">${q1}${val}${q2}</span>`
  )

  result = result.replace(
    /^(\s*\.[a-zA-Z0-9_-]+)(\s*\{)/gm,
    (_, sel, brace) => `<span class="selector">${sel}</span>${brace}`
  )
  result = result.replace(
    /^(\s+)([a-z-]+)(:)/gm,
    (_, space, prop, colon) =>
      `${space}<span class="property">${prop}</span>${colon}`
  )
  result = result.replace(
    /(:\s*)([^;\n}]+?)(;|$)/gm,
    (_, colon, val, end) =>
      `${colon}<span class="property-value">${val}</span>${end}`
  )

  return result
}
