import type { Contour, NestedNode } from './types'

function rectangleContains(
  outer: Contour,
  inner: Contour,
  tolerance: number = 2
): boolean {
  const innerLeft = inner.x
  const innerTop = inner.y
  const innerRight = inner.x + inner.width
  const innerBottom = inner.y + inner.height

  const outerLeft = outer.x - tolerance
  const outerTop = outer.y - tolerance
  const outerRight = outer.x + outer.width + tolerance
  const outerBottom = outer.y + outer.height + tolerance

  return (
    innerLeft >= outerLeft &&
    innerTop >= outerTop &&
    innerRight <= outerRight &&
    innerBottom <= outerBottom
  )
}

export function buildNestingTree(contours: Contour[]): NestedNode[] {
  if (contours.length === 0) return []

  const byId = new Map<string, NestedNode>()
  for (const c of contours) {
    c.parentId = null
    c.depth = 0
    byId.set(c.id, { contour: c, children: [] })
  }

  const sorted = [...contours].sort(
    (a, b) => b.width * b.height - a.width * a.height
  )

  for (let i = 0; i < sorted.length; i++) {
    const child = sorted[i]
    let directParent: Contour | null = null
    let directParentArea = Infinity

    for (let j = 0; j < i; j++) {
      const candidateParent = sorted[j]
      if (candidateParent.id === child.id) continue
      if (!rectangleContains(candidateParent, child)) continue

      const parentArea = candidateParent.width * candidateParent.height
      if (parentArea < directParentArea) {
        directParent = candidateParent
        directParentArea = parentArea
      }
    }

    if (directParent) {
      child.parentId = directParent.id
      const parentNode = byId.get(directParent.id)!
      const childNode = byId.get(child.id)!
      parentNode.children.push(childNode)
    }
  }

  const roots: NestedNode[] = []
  for (const c of sorted) {
    if (c.parentId === null) {
      roots.push(byId.get(c.id)!)
    }
  }

  function assignDepths(nodes: NestedNode[], currentDepth: number): void {
    for (const node of nodes) {
      node.contour.depth = currentDepth
      assignDepths(node.children, currentDepth + 1)
    }
  }
  assignDepths(roots, 0)

  roots.sort((a, b) => {
    const ay = a.contour.y
    const by = b.contour.y
    if (Math.abs(ay - by) > 20) return ay - by
    return a.contour.x - b.contour.x
  })

  function sortChildren(nodes: NestedNode[]): void {
    for (const n of nodes) {
      n.children.sort((a, b) => {
        const ay = a.contour.y - n.contour.y
        const by = b.contour.y - n.contour.y
        if (Math.abs(ay - by) > 20) return ay - by
        return (a.contour.x - n.contour.x) - (b.contour.x - n.contour.x)
      })
      sortChildren(n.children)
    }
  }
  sortChildren(roots)

  return roots
}

function indent(level: number): string {
  return '  '.repeat(level)
}

function generateClassName(contour: Contour, globalIndex: number): string {
  const depth = contour.depth
  if (depth === 0) {
    return `container-${globalIndex}`
  }
  if (depth === 1) {
    return `section-${globalIndex}`
  }
  if (depth === 2) {
    return `block-${globalIndex}`
  }
  return `l${depth}-el-${globalIndex}`
}

function round(n: number): number {
  return Math.round(n * 10) / 10
}

export interface GeneratedCode {
  html: string
  css: string
  combined: string
}

export function generateCode(contours: Contour[]): GeneratedCode {
  if (contours.length === 0) {
    return {
      html: '<!-- 暂无元素，先在画布上确认轮廓 -->',
      css: '/* 暂无样式 */',
      combined: '<!-- 暂无元素，先在画布上确认轮廓 -->'
    }
  }

  const tree = buildNestingTree(contours)

  const htmlLines: string[] = []
  const cssLines: string[] = []
  let globalCounter = 0

  cssLines.push('/* ====================================')
  cssLines.push(' * Generated by Design to Code Converter')
  cssLines.push(' * Contours: ' + contours.length + ' elements')
  cssLines.push(' * Max depth: L' + Math.max(...contours.map((c) => c.depth)))
  cssLines.push(' * ==================================== */')
  cssLines.push('')
  cssLines.push('* { box-sizing: border-box; margin: 0; padding: 0; }')
  cssLines.push('')

  function generateFromNode(
    node: NestedNode,
    indentLevel: number,
    parentNode?: NestedNode
  ) {
    globalCounter++
    const className = generateClassName(node.contour, globalCounter)

    const relX = parentNode
      ? round(node.contour.x - parentNode.contour.x)
      : round(node.contour.x)
    const relY = parentNode
      ? round(node.contour.y - parentNode.contour.y)
      : round(node.contour.y)

    const cssIndent = indent(1)
    cssLines.push(`.${className} {`)
    cssLines.push(`${cssIndent}/* depth: L${node.contour.depth} */`)
    cssLines.push(
      `${cssIndent}position: ${parentNode ? 'absolute' : 'relative'};`
    )
    if (parentNode) {
      cssLines.push(`${cssIndent}left: ${relX}px;`)
      cssLines.push(`${cssIndent}top: ${relY}px;`)
    }
    cssLines.push(`${cssIndent}width: ${round(node.contour.width)}px;`)
    cssLines.push(`${cssIndent}height: ${round(node.contour.height)}px;`)
    const alpha = 0.06 + node.contour.depth * 0.04
    cssLines.push(
      `${cssIndent}background: rgba(108, 99, 255, ${alpha.toFixed(2)});`
    )
    cssLines.push(`${cssIndent}border: 1px dashed rgba(108, 99, 255, 0.5);`)
    cssLines.push(`${cssIndent}border-radius: 4px;`)
    cssLines.push('}')
    cssLines.push('')

    if (node.children.length > 0) {
      cssLines.push(`/* Nested children of .${className} */`)
      for (let i = 0; i < node.contour.depth + 1 && i < 3; i++) {
        cssLines.push(`.${className} { /* nesting depth visual */ }`)
      }
      cssLines.push('')
    }

    const openTag = `${indent(indentLevel)}<div class="${className}">`
    htmlLines.push(openTag)

    if (node.children.length > 0) {
      for (const child of node.children) {
        generateFromNode(child, indentLevel + 1, node)
      }
    } else {
      htmlLines.push(
        `${indent(indentLevel + 1)}<!-- L${node.contour.depth} leaf: ${Math.round(
          node.contour.width
        )}×${Math.round(node.contour.height)} -->`
      )
    }

    htmlLines.push(`${indent(indentLevel)}</div>`)
  }

  const maxRight = Math.max(...contours.map((c) => c.x + c.width))
  const maxBottom = Math.max(...contours.map((c) => c.y + c.height))
  const rootPad = 16

  cssLines.push('.design-root {')
  cssLines.push(`${indent(1)}position: relative;`)
  cssLines.push(`${indent(1)}width: ${round(maxRight + rootPad * 2)}px;`)
  cssLines.push(`${indent(1)}height: ${round(maxBottom + rootPad * 2)}px;`)
  cssLines.push(`${indent(1)}padding: ${rootPad}px;`)
  cssLines.push(`${indent(1)}background: #f7f7fb;`)
  cssLines.push(`${indent(1)}font-family: sans-serif;`)
  cssLines.push('}')
  cssLines.push('')

  htmlLines.push('<div class="design-root">')
  for (const root of tree) {
    generateFromNode(root, 1)
  }
  htmlLines.push('</div>')

  const htmlStr = htmlLines.join('\n')
  const cssStr = cssLines.join('\n')
  const combined = `${cssStr}\n\n<!-- ================= HTML ================= -->\n${htmlStr}`

  return { html: htmlStr, css: cssStr, combined }
}

export function highlightCode(rawCode: string): string {
  const code = rawCode
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

  let result = code

  result = result.replace(
    /(\/\*[\s\S]*?\*\/)/g,
    '<span class="comment">$1</span>'
  )
  result = result.replace(
    /(&lt;!--[\s\S]*?--&gt;)/g,
    '<span class="comment">$1</span>'
  )

  result = result.replace(
    /(&lt;\/?)([a-zA-Z0-9-]+)/g,
    (_m, prefix: string, tag: string) =>
      `${prefix}<span class="tag">${tag}</span>`
  )

  result = result.replace(
    /(&lt;[a-zA-Z0-9-]+\s+)([a-zA-Z-]+)(=)(&quot;)(.*?)(&quot;)/g,
    (_m, prefix: string, name: string, eq: string, q1: string, val: string, q2: string) =>
      `${prefix}<span class="attr-name">${name}</span>${eq}<span class="attr-value">${q1}${val}${q2}</span>`
  )

  result = result.replace(
    /^( *)(\.[a-zA-Z0-9_-]+)(\s*\{)/gm,
    (_m, space: string, sel: string, brace: string) =>
      `${space}<span class="selector">${sel}</span>${brace}`
  )
  result = result.replace(
    /^( +)([a-z-]+)(:)/gm,
    (_m, space: string, prop: string, colon: string) =>
      `${space}<span class="property">${prop}</span>${colon}`
  )
  result = result.replace(
    /(:\s*)([^;\n}]+?)(;|$)/gm,
    (_m, colon: string, val: string, end: string) =>
      `${colon}<span class="property-value">${val}</span>${end}`
  )

  return result
}
