export interface Point {
  x: number;
  y: number;
}

export interface HSV {
  h: number;
  s: number;
  v: number;
}

export class LightPoint {
  public progress: number;
  public speed: number;
  public size: number;
  public pulsePhase: number;

  constructor(progress: number, speed: number = 1) {
    this.progress = progress;
    this.speed = speed;
    this.size = 2 + Math.random() * 3;
    this.pulsePhase = Math.random() * Math.PI * 2;
  }

  update(deltaTime: number, speedMultiplier: number = 1, globalSlowFactor: number = 1): void {
    this.progress += this.speed * deltaTime * 0.03 * speedMultiplier * globalSlowFactor;
    if (this.progress > 1) {
      this.progress -= 1;
    }
    this.pulsePhase += deltaTime * 0.005;
  }

  getCurrentSize(): number {
    return 2 + (Math.sin(this.pulsePhase) + 1) * 1.5;
  }
}

export class Node {
  public x: number;
  public y: number;
  public id: number;
  public color: HSV;
  public isEndpoint: boolean;
  public connectedNodeIds: Set<number>;
  public ripplePhase: number | null;
  public hoverScale: number;

  private static _idCounter = 0;

  constructor(x: number, y: number, color: HSV, isEndpoint: boolean = false) {
    this.x = x;
    this.y = y;
    this.id = Node._idCounter++;
    this.color = { ...color };
    this.isEndpoint = isEndpoint;
    this.connectedNodeIds = new Set();
    this.ripplePhase = null;
    this.hoverScale = 1;
  }

  distanceTo(other: Node): number {
    const dx = this.x - other.x;
    const dy = this.y - other.y;
    return Math.sqrt(dx * dx + dy * dy);
  }

  distanceToPoint(x: number, y: number): number {
    const dx = this.x - x;
    const dy = this.y - y;
    return Math.sqrt(dx * dx + dy * dy);
  }

  triggerRipple(): void {
    this.ripplePhase = 0;
  }

  updateRipple(deltaTime: number): boolean {
    if (this.ripplePhase === null) return false;
    this.ripplePhase += deltaTime / 600;
    if (this.ripplePhase >= 1) {
      this.ripplePhase = null;
      return false;
    }
    return true;
  }
}

export class Connection {
  public nodeA: Node;
  public nodeB: Node;
  public color: HSV;
  public lightPoints: LightPoint[];
  public bidirectional: boolean;
  public growthProgress: number;
  public highlightIntensity: number;
  public isAutoGenerated: boolean;

  constructor(nodeA: Node, nodeB: Node, color: HSV, bidirectional: boolean = false, isAutoGenerated: boolean = false) {
    this.nodeA = nodeA;
    this.nodeB = nodeB;
    this.color = { ...color };
    this.bidirectional = bidirectional;
    this.growthProgress = 0;
    this.highlightIntensity = 0;
    this.isAutoGenerated = isAutoGenerated;
    this.lightPoints = [];
    this.initLightPoints();
  }

  initLightPoints(): void {
    const count = this.bidirectional ? 2 : 1;
    for (let i = 0; i < count; i++) {
      const progress = count === 1 ? i : (i === 0 ? 0.25 : 0.75);
      const speed = count === 1 ? 1 : (i === 0 ? 1 : -1);
      this.lightPoints.push(new LightPoint(progress, speed));
    }
  }

  getPointAtProgress(progress: number): Point {
    const t = this.bidirectional ? progress : (this.lightPoints[0].speed > 0 ? progress : 1 - progress);
    return {
      x: this.nodeA.x + (this.nodeB.x - this.nodeA.x) * t,
      y: this.nodeA.y + (this.nodeB.y - this.nodeA.y) * t,
    };
  }

  update(deltaTime: number, speedMultiplier: number = 1, globalSlowFactor: number = 1): void {
    if (this.growthProgress < 1) {
      this.growthProgress = Math.min(1, this.growthProgress + deltaTime / 300);
    }
    if (this.highlightIntensity > 0) {
      this.highlightIntensity = Math.max(0, this.highlightIntensity - deltaTime / 400);
    }
    this.lightPoints.forEach((lp) => lp.update(deltaTime, speedMultiplier, globalSlowFactor));
  }

  triggerHighlight(): void {
    this.highlightIntensity = 1;
  }

  getLength(): number {
    return this.nodeA.distanceTo(this.nodeB);
  }
}

export class Trajectory {
  public id: number;
  public points: Point[];
  public startHue: number;
  public endHue: number;
  public connections: Connection[];
  public isComplete: boolean;
  public lightPoints: LightPoint[];
  public totalLength: number;
  public segmentLengths: number[];
  public opacity: number;
  public fadeProgress: number;

  private static _idCounter = 0;

  constructor(startPoint: Point, startHue: number) {
    this.id = Trajectory._idCounter++;
    this.points = [startPoint];
    this.startHue = startHue;
    this.endHue = startHue;
    this.connections = [];
    this.isComplete = false;
    this.lightPoints = [];
    this.totalLength = 0;
    this.segmentLengths = [];
    this.opacity = 1;
    this.fadeProgress = 1;
  }

  addPoint(point: Point, hue: number): void {
    if (this.points.length === 0) return;
    const lastPoint = this.points[this.points.length - 1];
    const dx = point.x - lastPoint.x;
    const dy = point.y - lastPoint.y;
    const dist = Math.sqrt(dx * dx + dy * dy);

    if (dist < 5) return;

    this.points.push(point);
    this.segmentLengths.push(dist);
    this.totalLength += dist;
    this.endHue = hue;

    this.lightPoints = [];
    const spacing = 10;
    const count = Math.max(1, Math.floor(this.totalLength / spacing));
    for (let i = 0; i < count; i++) {
      this.lightPoints.push(new LightPoint(i / count, 1));
    }
  }

  complete(): void {
    this.isComplete = true;
  }

  getPointAtDistance(distance: number): Point {
    if (this.points.length < 2 || this.totalLength === 0) {
      return { ...this.points[0] };
    }

    let remaining = Math.max(0, Math.min(distance, this.totalLength));
    for (let i = 0; i < this.segmentLengths.length; i++) {
      if (remaining <= this.segmentLengths[i]) {
        const t = this.segmentLengths[i] === 0 ? 0 : remaining / this.segmentLengths[i];
        const p1 = this.points[i];
        const p2 = this.points[i + 1];
        return {
          x: p1.x + (p2.x - p1.x) * t,
          y: p1.y + (p2.y - p1.y) * t,
        };
      }
      remaining -= this.segmentLengths[i];
    }
    return { ...this.points[this.points.length - 1] };
  }

  getHueAtDistance(distance: number): number {
    const t = this.totalLength === 0 ? 0 : distance / this.totalLength;
    return this.startHue + (this.endHue - this.startHue) * t;
  }

  getStartPoint(): Point {
    return { ...this.points[0] };
  }

  getEndPoint(): Point {
    return { ...this.points[this.points.length - 1] };
  }

  updateLightPoints(deltaTime: number, speedMultiplier: number = 1, globalSlowFactor: number = 1): void {
    this.lightPoints.forEach((lp) => lp.update(deltaTime, speedMultiplier, globalSlowFactor));
  }

  updateFade(deltaTime: number, fading: boolean): boolean {
    if (fading) {
      this.fadeProgress = Math.max(0, this.fadeProgress - deltaTime / 800);
      this.opacity = this.fadeProgress;
      return this.fadeProgress > 0;
    }
    return true;
  }
}

export class Network {
  public trajectories: Trajectory[];
  public nodes: Node[];
  public connections: Connection[];
  public currentTrajectory: Trajectory | null;
  public distanceThreshold: number;
  public isFading: boolean;
  public fadeCenter: Point | null;
  public fadeRadius: number;
  public maxTrajectories: number;
  public maxNodes: number;

  constructor() {
    this.trajectories = [];
    this.nodes = [];
    this.connections = [];
    this.currentTrajectory = null;
    this.distanceThreshold = 80;
    this.isFading = false;
    this.fadeCenter = null;
    this.fadeRadius = 0;
    this.maxTrajectories = 200;
    this.maxNodes = 500;
  }

  startTrajectory(point: Point, hue: number): void {
    if (this.trajectories.length >= this.maxTrajectories) return;
    this.currentTrajectory = new Trajectory(point, hue);
    this.trajectories.push(this.currentTrajectory);
  }

  addTrajectoryPoint(point: Point, hue: number): void {
    if (!this.currentTrajectory) return;
    this.currentTrajectory.addPoint(point, hue);
  }

  completeTrajectory(): void {
    if (!this.currentTrajectory) return;
    this.currentTrajectory.complete();
    this.createNodesAndConnect(this.currentTrajectory);
    this.currentTrajectory = null;
  }

  createNodesAndConnect(trajectory: Trajectory): void {
    if (trajectory.points.length < 2) return;

    const startNode = new Node(
      trajectory.getStartPoint().x,
      trajectory.getStartPoint().y,
      { h: trajectory.startHue, s: 80, v: 100 },
      true
    );
    const endNode = new Node(
      trajectory.getEndPoint().x,
      trajectory.getEndPoint().y,
      { h: trajectory.endHue, s: 80, v: 100 },
      true
    );

    if (this.nodes.length < this.maxNodes - 2) {
      this.nodes.push(startNode, endNode);
      this.autoConnectToNearbyNodes(startNode);
      this.autoConnectToNearbyNodes(endNode);
      this.checkIntermediateConnections(trajectory);
    }
  }

  autoConnectToNearbyNodes(node: Node): void {
    for (const other of this.nodes) {
      if (other.id === node.id) continue;
      if (node.connectedNodeIds.has(other.id)) continue;

      const dist = node.distanceTo(other);
      if (dist < this.distanceThreshold && dist > 0) {
        const mixedHue = (node.color.h + other.color.h) / 2;
        const connection = new Connection(
          node,
          other,
          { h: mixedHue, s: 70, v: 90 },
          true,
          true
        );
        node.connectedNodeIds.add(other.id);
        other.connectedNodeIds.add(node.id);
        this.connections.push(connection);
      }
    }
  }

  checkIntermediateConnections(trajectory: Trajectory): void {
    if (trajectory.points.length < 5) return;

    const sampleIndices = [
      Math.floor(trajectory.points.length * 0.25),
      Math.floor(trajectory.points.length * 0.5),
      Math.floor(trajectory.points.length * 0.75),
    ];

    for (const idx of sampleIndices) {
      const point = trajectory.points[idx];
      const hue = trajectory.getHueAtDistance(idx * (trajectory.totalLength / trajectory.points.length));

      for (const node of this.nodes) {
        if (node.connectedNodeIds.has(-1)) continue;
        const dist = node.distanceToPoint(point.x, point.y);
        if (dist < this.distanceThreshold && dist > 0) {
          if (this.nodes.length >= this.maxNodes) break;

          const newNode = new Node(point.x, point.y, { h: hue, s: 80, v: 100 }, false);
          this.nodes.push(newNode);

          const mixedHue = (hue + node.color.h) / 2;
          const connection = new Connection(
            newNode,
            node,
            { h: mixedHue, s: 70, v: 90 },
            true,
            true
          );
          newNode.connectedNodeIds.add(node.id);
          node.connectedNodeIds.add(newNode.id);
          this.connections.push(connection);

          this.autoConnectToNearbyNodes(newNode);
          break;
        }
      }
    }
  }

  findHoveredNode(x: number, y: number, radius: number = 15): Node | null {
    for (const node of this.nodes) {
      if (node.distanceToPoint(x, y) < radius) {
        return node;
      }
    }
    return null;
  }

  triggerRippleAtNode(node: Node): void {
    node.triggerRipple();
    for (const connection of this.connections) {
      if (connection.nodeA.id === node.id || connection.nodeB.id === node.id) {
        connection.triggerHighlight();
      }
    }
  }

  startFadeAnimation(center: Point): void {
    this.isFading = true;
    this.fadeCenter = center;
    this.fadeRadius = 0;
  }

  update(deltaTime: number, speedMultiplier: number = 1, globalSlowFactor: number = 1): void {
    for (const trajectory of this.trajectories) {
      trajectory.updateLightPoints(deltaTime, speedMultiplier, globalSlowFactor);
      if (this.isFading) {
        const surviving = trajectory.updateFade(deltaTime, true);
        if (!surviving) {
          const idx = this.trajectories.indexOf(trajectory);
          if (idx > -1) this.trajectories.splice(idx, 1);
        }
      }
    }

    for (const connection of this.connections) {
      connection.update(deltaTime, speedMultiplier, globalSlowFactor);
    }

    for (const node of this.nodes) {
      node.updateRipple(deltaTime);
      if (node.hoverScale > 1) {
        node.hoverScale = Math.max(1, node.hoverScale - deltaTime / 300);
      }
    }

    if (this.isFading) {
      this.fadeRadius += deltaTime * 2;
      const maxDist = Math.max(
        this.fadeCenter ? this.fadeCenter.x + this.fadeCenter.y : 2000,
        2000
      );
      if (this.fadeRadius > maxDist) {
        this.clearAll();
      }
    }
  }

  clearAll(): void {
    this.trajectories = [];
    this.nodes = [];
    this.connections = [];
    this.currentTrajectory = null;
    this.isFading = false;
    this.fadeCenter = null;
    this.fadeRadius = 0;
  }
}
