export interface Word {
  word: string;
  meaning: string;
  pos: string;
}

export interface WordList {
  easy: Word[];
  medium: Word[];
  hard: Word[];
}

export const mockWords: WordList = {
  easy: [
    { word: "apple", meaning: "苹果", pos: "n." },
    { word: "book", meaning: "书", pos: "n." },
    { word: "cat", meaning: "猫", pos: "n." },
    { word: "dog", meaning: "狗", pos: "n." },
    { word: "egg", meaning: "鸡蛋", pos: "n." },
    { word: "fish", meaning: "鱼", pos: "n." },
    { word: "good", meaning: "好的", pos: "adj." },
    { word: "happy", meaning: "快乐的", pos: "adj." },
    { word: "ice", meaning: "冰", pos: "n." },
    { word: "jump", meaning: "跳", pos: "v." },
    { word: "king", meaning: "国王", pos: "n." },
    { word: "love", meaning: "爱", pos: "v./n." },
    { word: "milk", meaning: "牛奶", pos: "n." },
    { word: "name", meaning: "名字", pos: "n." },
    { word: "open", meaning: "打开", pos: "v." },
    { word: "play", meaning: "玩", pos: "v." },
    { word: "queen", meaning: "女王", pos: "n." },
    { word: "run", meaning: "跑", pos: "v." },
    { word: "sun", meaning: "太阳", pos: "n." },
    { word: "tree", meaning: "树", pos: "n." },
    { word: "up", meaning: "向上", pos: "adv." },
    { word: "water", meaning: "水", pos: "n." },
    { word: "yes", meaning: "是的", pos: "adv." },
    { word: "zero", meaning: "零", pos: "num." },
    { word: "big", meaning: "大的", pos: "adj." },
    { word: "small", meaning: "小的", pos: "adj." },
    { word: "red", meaning: "红色", pos: "n./adj." },
    { word: "blue", meaning: "蓝色", pos: "n./adj." },
    { word: "green", meaning: "绿色", pos: "n./adj." },
    { word: "yellow", meaning: "黄色", pos: "n./adj." },
    { word: "white", meaning: "白色", pos: "n./adj." },
    { word: "black", meaning: "黑色", pos: "n./adj." },
    { word: "hot", meaning: "热的", pos: "adj." },
    { word: "cold", meaning: "冷的", pos: "adj." },
    { word: "new", meaning: "新的", pos: "adj." },
    { word: "old", meaning: "老的", pos: "adj." },
    { word: "fast", meaning: "快的", pos: "adj." },
    { word: "slow", meaning: "慢的", pos: "adj." },
    { word: "eat", meaning: "吃", pos: "v." },
    { word: "drink", meaning: "喝", pos: "v." },
    { word: "sleep", meaning: "睡觉", pos: "v." },
    { word: "walk", meaning: "走路", pos: "v." },
    { word: "read", meaning: "阅读", pos: "v." },
    { word: "write", meaning: "写", pos: "v." },
    { word: "sing", meaning: "唱歌", pos: "v." },
    { word: "dance", meaning: "跳舞", pos: "v." },
    { word: "draw", meaning: "画画", pos: "v." },
    { word: "speak", meaning: "说话", pos: "v." },
    { word: "listen", meaning: "听", pos: "v." },
    { word: "watch", meaning: "观看", pos: "v." },
    { word: "see", meaning: "看见", pos: "v." },
    { word: "hear", meaning: "听见", pos: "v." },
    { word: "think", meaning: "思考", pos: "v." },
    { word: "know", meaning: "知道", pos: "v." },
    { word: "learn", meaning: "学习", pos: "v." },
    { word: "teach", meaning: "教", pos: "v." },
    { word: "help", meaning: "帮助", pos: "v." },
    { word: "like", meaning: "喜欢", pos: "v." },
    { word: "want", meaning: "想要", pos: "v." },
    { word: "need", meaning: "需要", pos: "v." },
    { word: "have", meaning: "有", pos: "v." },
    { word: "do", meaning: "做", pos: "v." },
    { word: "go", meaning: "去", pos: "v." },
    { word: "come", meaning: "来", pos: "v." },
    { word: "take", meaning: "拿", pos: "v." },
    { word: "make", meaning: "制作", pos: "v." },
    { word: "give", meaning: "给", pos: "v." },
    { word: "get", meaning: "得到", pos: "v." },
    { word: "use", meaning: "使用", pos: "v." },
    { word: "find", meaning: "找到", pos: "v." },
    { word: "lose", meaning: "丢失", pos: "v." },
  ],
  medium: [
    { word: "achieve", meaning: "实现，达成", pos: "v." },
    { word: "beautiful", meaning: "美丽的", pos: "adj." },
    { word: "celebrate", meaning: "庆祝", pos: "v." },
    { word: "decision", meaning: "决定", pos: "n." },
    { word: "education", meaning: "教育", pos: "n." },
    { word: "familiar", meaning: "熟悉的", pos: "adj." },
    { word: "generous", meaning: "慷慨的", pos: "adj." },
    { word: "horizon", meaning: "地平线", pos: "n." },
    { word: "important", meaning: "重要的", pos: "adj." },
    { word: "journey", meaning: "旅程", pos: "n." },
    { word: "knowledge", meaning: "知识", pos: "n." },
    { word: "language", meaning: "语言", pos: "n." },
    { word: "magnificent", meaning: "壮丽的", pos: "adj." },
    { word: "necessary", meaning: "必要的", pos: "adj." },
    { word: "opportunity", meaning: "机会", pos: "n." },
    { word: "particular", meaning: "特别的", pos: "adj." },
    { word: "question", meaning: "问题", pos: "n." },
    { word: "remarkable", meaning: "非凡的", pos: "adj." },
    { word: "situation", meaning: "情况", pos: "n." },
    { word: "tradition", meaning: "传统", pos: "n." },
    { word: "unusual", meaning: "不寻常的", pos: "adj." },
    { word: "valuable", meaning: "有价值的", pos: "adj." },
    { word: "wonderful", meaning: "精彩的", pos: "adj." },
    { word: "yesterday", meaning: "昨天", pos: "n." },
    { word: "accomplish", meaning: "完成", pos: "v." },
    { word: "brilliant", meaning: "杰出的", pos: "adj." },
    { word: "challenge", meaning: "挑战", pos: "n./v." },
    { word: "develop", meaning: "发展", pos: "v." },
    { word: "environment", meaning: "环境", pos: "n." },
    { word: "fantastic", meaning: "极好的", pos: "adj." },
    { word: "government", meaning: "政府", pos: "n." },
    { word: "historical", meaning: "历史的", pos: "adj." },
    { word: "industry", meaning: "工业", pos: "n." },
    { word: "justice", meaning: "正义", pos: "n." },
    { word: "literature", meaning: "文学", pos: "n." },
    { word: "mysterious", meaning: "神秘的", pos: "adj." },
    { word: "negotiate", meaning: "谈判", pos: "v." },
    { word: "organization", meaning: "组织", pos: "n." },
    { word: "performance", meaning: "表演", pos: "n." },
    { word: "quality", meaning: "质量", pos: "n." },
    { word: "reference", meaning: "参考", pos: "n." },
    { word: "significant", meaning: "重要的", pos: "adj." },
    { word: "technology", meaning: "技术", pos: "n." },
    { word: "understand", meaning: "理解", pos: "v." },
    { word: "volunteer", meaning: "志愿者", pos: "n." },
    { word: "weather", meaning: "天气", pos: "n." },
    { word: "experience", meaning: "经验", pos: "n." },
    { word: "approach", meaning: "方法", pos: "n." },
    { word: "consider", meaning: "考虑", pos: "v." },
    { word: "describe", meaning: "描述", pos: "v." },
    { word: "establish", meaning: "建立", pos: "v." },
    { word: "focus", meaning: "聚焦", pos: "v." },
    { word: "generate", meaning: "产生", pos: "v." },
    { word: "improve", meaning: "改善", pos: "v." },
    { word: "maintain", meaning: "维持", pos: "v." },
    { word: "prevent", meaning: "阻止", pos: "v." },
    { word: "require", meaning: "要求", pos: "v." },
    { word: "separate", meaning: "分离", pos: "v." },
    { word: "support", meaning: "支持", pos: "v." },
    { word: "survive", meaning: "幸存", pos: "v." },
  ],
  hard: [
    { word: "abbreviation", meaning: "缩写", pos: "n." },
    { word: "bureaucracy", meaning: "官僚主义", pos: "n." },
    { word: "consequence", meaning: "后果", pos: "n." },
    { word: "deteriorate", meaning: "恶化", pos: "v." },
    { word: "eccentricity", meaning: "古怪", pos: "n." },
    { word: "fluorescent", meaning: "荧光的", pos: "adj." },
    { word: "gregarious", meaning: "群居的", pos: "adj." },
    { word: "hierarchical", meaning: "等级制的", pos: "adj." },
    { word: "idiosyncratic", meaning: "特异的", pos: "adj." },
    { word: "juxtaposition", meaning: "并列", pos: "n." },
    { word: "kaleidoscope", meaning: "万花筒", pos: "n." },
    { word: "labyrinthine", meaning: "迷宫般的", pos: "adj." },
    { word: "metamorphosis", meaning: "变形", pos: "n." },
    { word: "nonchalant", meaning: "冷淡的", pos: "adj." },
    { word: "obsequious", meaning: "谄媚的", pos: "adj." },
    { word: "paradigm", meaning: "范式", pos: "n." },
    { word: "quintessential", meaning: "典型的", pos: "adj." },
    { word: "reconnaissance", meaning: "侦察", pos: "n." },
    { word: "sophisticated", meaning: "复杂的", pos: "adj." },
    { word: "transgression", meaning: "违反", pos: "n." },
    { word: "ubiquitous", meaning: "无处不在的", pos: "adj." },
    { word: "vicissitude", meaning: "变迁", pos: "n." },
    { word: "whimsical", meaning: "异想天开的", pos: "adj." },
    { word: "xenophobia", meaning: "仇外心理", pos: "n." },
    { word: "zealot", meaning: "狂热者", pos: "n." },
    { word: "ambiguous", meaning: "模棱两可的", pos: "adj." },
    { word: "benevolent", meaning: "仁慈的", pos: "adj." },
    { word: "clandestine", meaning: "秘密的", pos: "adj." },
    { word: "discrepancy", meaning: "差异", pos: "n." },
    { word: "ephemeral", meaning: "短暂的", pos: "adj." },
    { word: "fastidious", meaning: "挑剔的", pos: "adj." },
    { word: "garrulous", meaning: "唠叨的", pos: "adj." },
    { word: "heterogeneous", meaning: "异质的", pos: "adj." },
    { word: "impeccable", meaning: "无可挑剔的", pos: "adj." },
    { word: "juxtapose", meaning: "并列", pos: "v." },
    { word: "laconic", meaning: "简洁的", pos: "adj." },
    { word: "magnanimous", meaning: "宽宏大量的", pos: "adj." },
    { word: "nefarious", meaning: "邪恶的", pos: "adj." },
    { word: "ostentatious", meaning: "炫耀的", pos: "adj." },
    { word: "perfunctory", meaning: "敷衍的", pos: "adj." },
    { word: "quagmire", meaning: "困境", pos: "n." },
    { word: "recalcitrant", meaning: "顽抗的", pos: "adj." },
    { word: "surreptitious", meaning: "秘密的", pos: "adj." },
    { word: "tenacious", meaning: "坚韧的", pos: "adj." },
    { word: "unctuous", meaning: "油嘴滑舌的", pos: "adj." },
    { word: "vituperative", meaning: "辱骂的", pos: "adj." },
    { word: "wistful", meaning: "渴望的", pos: "adj." },
    { word: "apotheosis", meaning: "神化", pos: "n." },
    { word: "bellicose", meaning: "好战的", pos: "adj." },
    { word: "circumlocution", meaning: "迂回说法", pos: "n." },
    { word: "disingenuous", meaning: "不真诚的", pos: "adj." },
    { word: "ebullient", meaning: "热情洋溢的", pos: "adj." },
    { word: "facilitate", meaning: "促进", pos: "v." },
    { word: "gratuitous", meaning: "无端的", pos: "adj." },
    { word: "hackneyed", meaning: "陈腐的", pos: "adj." },
    { word: "iconoclast", meaning: "偶像破坏者", pos: "n." },
    { word: "indefatigable", meaning: "不知疲倦的", pos: "adj." },
    { word: "judicature", meaning: "司法", pos: "n." },
    { word: "lethargic", meaning: "昏昏欲睡的", pos: "adj." },
    { word: "monolithic", meaning: "整体的", pos: "adj." },
    { word: "nihilism", meaning: "虚无主义", pos: "n." },
    { word: "obfuscate", meaning: "使模糊", pos: "v." },
    { word: "peripatetic", meaning: "漫游的", pos: "adj." },
    { word: "quixotic", meaning: "不切实际的", pos: "adj." },
    { word: "recrimination", meaning: "反控", pos: "n." },
    { word: "sycophant", meaning: "谄媚者", pos: "n." },
    { word: "tendentious", meaning: "有倾向性的", pos: "adj." },
    { word: "umbrage", meaning: "不悦", pos: "n." },
    { word: "verisimilitude", meaning: "逼真", pos: "n." },
    { word: "welter", meaning: "混乱", pos: "n." },
  ],
};

export const getRandomWord = (difficulty: "easy" | "medium" | "hard"): Word => {
  const words = mockWords[difficulty];
  return words[Math.floor(Math.random() * words.length)];
};

export default mockWords;
