import type { ColorToken, TypographyToken, SpacingValue } from '../types';

const COLOR_NAMES = [
  'primary',
  'secondary',
  'accent',
  'neutral',
  'success',
  'warning',
  'info',
  'error',
];

export function generateCSS(
  colors: ColorToken[],
  typography: TypographyToken,
  spacings: SpacingValue[],
): string {
  const lines: string[] = [];

  lines.push('/* Design Tokens - Generated by Design Tokens Studio */');
  lines.push('');
  lines.push(':root {');

  colors.forEach((color, index) => {
    const name = COLOR_NAMES[index] || `color-${index + 1}`;
    lines.push(`  --color-${name}: ${color.hex};`);
  });

  lines.push('');
  lines.push(`  --font-family: '${typography.fontFamily}', sans-serif;`);
  lines.push(`  --font-size: ${typography.fontSize}px;`);
  lines.push(`  --font-weight: ${typography.fontWeight};`);
  lines.push(`  --line-height: ${typography.lineHeight};`);
  lines.push('}');
  lines.push('');

  lines.push('.typography-preview {');
  lines.push(`  font-family: '${typography.fontFamily}', sans-serif;`);
  lines.push(`  font-size: ${typography.fontSize}px;`);
  lines.push(`  font-weight: ${typography.fontWeight};`);
  lines.push(`  line-height: ${typography.lineHeight};`);
  lines.push('}');
  lines.push('');

  if (spacings.length > 0) {
    lines.push('/* Spacing Tokens */');
    spacings.forEach((spacing, index) => {
      lines.push(`.spacing-${index + 1} {`);
      const prop = spacing.orientation === 'horizontal' ? 'margin' : 'padding';
      lines.push(`  ${prop}: ${spacing.distance}px;`);
      lines.push('}');
      lines.push('');
    });
  }

  return lines.join('\n');
}

export function downloadCSSFile(content: string, filename = 'design-tokens.css'): void {
  const blob = new Blob([content], { type: 'text/css;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
