import Datastore from 'nedb-promises';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dataDir = path.join(__dirname, 'data');
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const dbPath = path.join(dataDir, 'planets.db');
const db = Datastore.create({ filename: dbPath, autoload: true });

const planets = [
  {
    id: 'mercury',
    name: '水星',
    type: '类地行星',
    mass: '3.30 × 10²³ kg',
    radius: 2439.7,
    color: '#a0a0a0',
    orbitRadius: 57.9,
    orbitSpeed: 47.4,
    hasRings: false,
    description: '水星是太阳系八大行星中最小的行星，也是离太阳最近的行星。它的表面布满了陨石坑，外观类似月球，没有大气层保护。',
    orbitPeriod: '87.97 地球日',
    avgTemperature: '167°C (白天 430°C, 夜间 -180°C)',
    gravity: '3.7 m/s²',
    dayLength: '58.6 地球日',
    moons: 0,
    discoveredBy: '古代天文学家',
    discoveryDate: '公元前 3000 年',
  },
  {
    id: 'venus',
    name: '金星',
    type: '类地行星',
    mass: '4.87 × 10²⁴ kg',
    radius: 6051.8,
    color: '#e6c66e',
    orbitRadius: 108.2,
    orbitSpeed: 35.0,
    hasRings: false,
    description: '金星是太阳系中最热的行星，有着浓厚的二氧化碳大气层和硫酸云。它是夜空中最亮的行星，被称为"启明星"或"长庚星"。',
    orbitPeriod: '224.7 地球日',
    avgTemperature: '464°C',
    gravity: '8.87 m/s²',
    dayLength: '243 地球日 (逆向自转)',
    moons: 0,
    discoveredBy: '古代天文学家',
    discoveryDate: '公元前 3000 年',
  },
  {
    id: 'earth',
    name: '地球',
    type: '类地行星',
    mass: '5.97 × 10²⁴ kg',
    radius: 6371,
    color: '#3b82f6',
    orbitRadius: 149.6,
    orbitSpeed: 29.8,
    hasRings: false,
    description: '地球是太阳系中唯一已知存在生命的行星。它有液态水、适宜的大气层和磁场保护，是人类和数百万物种的家园。',
    orbitPeriod: '365.25 天',
    avgTemperature: '15°C',
    gravity: '9.81 m/s²',
    dayLength: '24 小时',
    moons: 1,
    discoveredBy: '不适用',
    discoveryDate: '不适用',
  },
  {
    id: 'mars',
    name: '火星',
    type: '类地行星',
    mass: '6.42 × 10²³ kg',
    radius: 3389.5,
    color: '#c0392b',
    orbitRadius: 227.9,
    orbitSpeed: 24.1,
    hasRings: false,
    description: '火星因其红色外观而被称为"红色星球"。它有太阳系最高的火山（奥林帕斯山）和最深的峡谷（水手谷），是人类殖民的主要目标。',
    orbitPeriod: '687 地球日',
    avgTemperature: '-63°C',
    gravity: '3.71 m/s²',
    dayLength: '24.6 小时',
    moons: 2,
    discoveredBy: '古代天文学家',
    discoveryDate: '公元前 3000 年',
  },
  {
    id: 'jupiter',
    name: '木星',
    type: '气态巨行星',
    mass: '1.90 × 10²⁷ kg',
    radius: 69911,
    color: '#d4a373',
    orbitRadius: 778.5,
    orbitSpeed: 13.1,
    hasRings: false,
    description: '木星是太阳系中最大的行星，质量是其他所有行星总和的2.5倍。著名的大红斑是一个持续了数百年的巨大风暴。',
    orbitPeriod: '11.86 地球年',
    avgTemperature: '-108°C (云顶)',
    gravity: '24.79 m/s²',
    dayLength: '9.9 小时',
    moons: 95,
    discoveredBy: '伽利略',
    discoveryDate: '1610 年',
  },
  {
    id: 'saturn',
    name: '土星',
    type: '气态巨行星',
    mass: '5.68 × 10²⁶ kg',
    radius: 58232,
    color: '#e2d3b0',
    orbitRadius: 1434,
    orbitSpeed: 9.7,
    hasRings: true,
    description: '土星以其壮观的光环系统而闻名，光环主要由冰和岩石碎片组成。它的密度比水还低，如果有足够大的海洋，土星会漂浮起来。',
    orbitPeriod: '29.46 地球年',
    avgTemperature: '-139°C (云顶)',
    gravity: '10.44 m/s²',
    dayLength: '10.7 小时',
    moons: 146,
    discoveredBy: '伽利略',
    discoveryDate: '1610 年',
  },
  {
    id: 'uranus',
    name: '天王星',
    type: '冰巨行星',
    mass: '8.68 × 10²⁵ kg',
    radius: 25362,
    color: '#a0d2db',
    orbitRadius: 2871,
    orbitSpeed: 6.8,
    hasRings: false,
    description: '天王星是太阳系中最冷的行星，它独特之处在于自转轴几乎与公转轨道平面平行，像是"躺着"旋转。',
    orbitPeriod: '84.01 地球年',
    avgTemperature: '-197°C (云顶)',
    gravity: '8.87 m/s²',
    dayLength: '17.2 小时',
    moons: 27,
    discoveredBy: '威廉·赫歇尔',
    discoveryDate: '1781 年',
  },
  {
    id: 'neptune',
    name: '海王星',
    type: '冰巨行星',
    mass: '1.02 × 10²⁶ kg',
    radius: 24622,
    color: '#3457d5',
    orbitRadius: 4495,
    orbitSpeed: 5.4,
    hasRings: false,
    description: '海王星是太阳系最外层的行星，有着太阳系中最强的风，风速可达2100公里/小时。它深邃的蓝色来自大气中的甲烷。',
    orbitPeriod: '164.8 地球年',
    avgTemperature: '-201°C (云顶)',
    gravity: '11.15 m/s²',
    dayLength: '16.1 小时',
    moons: 16,
    discoveredBy: '伽勒/勒维耶',
    discoveryDate: '1846 年',
  },
  {
    id: 'moon',
    name: '月球',
    type: '卫星',
    mass: '7.34 × 10²² kg',
    radius: 1737.4,
    color: '#cccccc',
    orbitRadius: 149.6,
    orbitSpeed: 1.0,
    hasRings: false,
    parentPlanet: 'earth',
    description: '月球是地球唯一的天然卫星，是人类唯一登陆过的地外天体。它的引力引起地球潮汐，也稳定了地球的自转轴。',
    orbitPeriod: '27.3 天',
    avgTemperature: '-53°C (白天 107°C, 夜间 -153°C)',
    gravity: '1.62 m/s²',
    dayLength: '27.3 地球日',
    moons: 0,
    discoveredBy: '古代人类',
    discoveryDate: '史前时代',
  },
  {
    id: 'phobos',
    name: '火卫一',
    type: '卫星',
    mass: '1.07 × 10¹⁶ kg',
    radius: 11.267,
    color: '#8b7355',
    orbitRadius: 227.9,
    orbitSpeed: 0.05,
    hasRings: false,
    parentPlanet: 'mars',
    description: '火卫一是火星两颗卫星中较大的一颗，形状不规则。它正在缓慢靠近火星，约5000万年后可能撞向火星或形成光环。',
    orbitPeriod: '7 小时 39 分',
    avgTemperature: '-40°C',
    gravity: '0.0057 m/s²',
    dayLength: '7 小时 39 分',
    moons: 0,
    discoveredBy: '阿萨夫·霍尔',
    discoveryDate: '1877 年',
  },
  {
    id: 'deimos',
    name: '火卫二',
    type: '卫星',
    mass: '1.48 × 10¹⁵ kg',
    radius: 6.2,
    color: '#9a8b7a',
    orbitRadius: 227.9,
    orbitSpeed: 0.02,
    hasRings: false,
    parentPlanet: 'mars',
    description: '火卫二是火星较小的卫星，形状不规则。它可能是被火星引力捕获的小行星，表面相对平滑，有更多的表岩屑覆盖。',
    orbitPeriod: '30.3 小时',
    avgTemperature: '-40°C',
    gravity: '0.003 m/s²',
    dayLength: '30.3 小时',
    moons: 0,
    discoveredBy: '阿萨夫·霍尔',
    discoveryDate: '1877 年',
  },
];

async function seedDatabase() {
  try {
    await db.remove({}, { multi: true });
    await db.insert(planets);
    console.log(`Seeded ${planets.length} celestial bodies into database`);
    console.log('Database location:', dbPath);
  } catch (error) {
    console.error('Error seeding database:', error);
  }
}

seedDatabase().then(() => {
  process.exit(0);
});
