import type { WordEntry } from './types';

const wordDatabase: WordEntry[] = [
  { word: 'accomplish', simplified: 'do', definition: '完成', frequency: 1, level: 2 },
  { word: 'acquire', simplified: 'get', definition: '获得', frequency: 2, level: 2 },
  { word: 'advantage', simplified: 'benefit', definition: '优势', frequency: 3, level: 1 },
  { word: 'analysis', simplified: 'study', definition: '分析', frequency: 4, level: 2 },
  { word: 'approach', simplified: 'way', definition: '方法', frequency: 5, level: 1 },
  { word: 'appropriate', simplified: 'right', definition: '适当的', frequency: 6, level: 2 },
  { word: 'assess', simplified: 'judge', definition: '评估', frequency: 7, level: 3 },
  { word: 'assume', simplified: 'think', definition: '假设', frequency: 8, level: 2 },
  { word: 'authority', simplified: 'power', definition: '权威', frequency: 9, level: 2 },
  { word: 'available', simplified: 'ready', definition: '可用的', frequency: 10, level: 1 },
  { word: 'beneficial', simplified: 'good', definition: '有益的', frequency: 11, level: 2 },
  { word: 'challenge', simplified: 'test', definition: '挑战', frequency: 12, level: 1 },
  { word: 'circumstance', simplified: 'situation', definition: '情况', frequency: 13, level: 2 },
  { word: 'communicate', simplified: 'talk', definition: '交流', frequency: 14, level: 2 },
  { word: 'concentrate', simplified: 'focus', definition: '集中', frequency: 15, level: 2 },
  { word: 'consequence', simplified: 'result', definition: '结果', frequency: 16, level: 2 },
  { word: 'consider', simplified: 'think', definition: '考虑', frequency: 17, level: 1 },
  { word: 'construct', simplified: 'build', definition: '建造', frequency: 18, level: 2 },
  { word: 'contribute', simplified: 'add', definition: '贡献', frequency: 19, level: 2 },
  { word: 'convenience', simplified: 'ease', definition: '便利', frequency: 20, level: 2 },
  { word: 'convince', simplified: 'persuade', definition: '说服', frequency: 21, level: 3 },
  { word: 'demonstrate', simplified: 'show', definition: '展示', frequency: 22, level: 2 },
  { word: 'determine', simplified: 'decide', definition: '决定', frequency: 23, level: 2 },
  { word: 'develop', simplified: 'grow', definition: '发展', frequency: 24, level: 1 },
  { word: 'discover', simplified: 'find', definition: '发现', frequency: 25, level: 1 },
  { word: 'efficient', simplified: 'fast', definition: '高效的', frequency: 26, level: 2 },
  { word: 'eliminate', simplified: 'remove', definition: '消除', frequency: 27, level: 3 },
  { word: 'emphasize', simplified: 'stress', definition: '强调', frequency: 28, level: 3 },
  { word: 'encounter', simplified: 'meet', definition: '遇到', frequency: 29, level: 2 },
  { word: 'establish', simplified: 'set up', definition: '建立', frequency: 30, level: 2 },
  { word: 'evaluate', simplified: 'rate', definition: '评价', frequency: 31, level: 3 },
  { word: 'evidence', simplified: 'proof', definition: '证据', frequency: 32, level: 2 },
  { word: 'examine', simplified: 'check', definition: '检查', frequency: 33, level: 2 },
  { word: 'experience', simplified: 'event', definition: '经历', frequency: 34, level: 1 },
  { word: 'facilitate', simplified: 'help', definition: '促进', frequency: 35, level: 3 },
  { word: 'familiar', simplified: 'known', definition: '熟悉的', frequency: 36, level: 2 },
  { word: 'focus', simplified: 'center', definition: '焦点', frequency: 37, level: 1 },
  { word: 'furthermore', simplified: 'also', definition: '此外', frequency: 38, level: 3 },
  { word: 'generate', simplified: 'make', definition: '产生', frequency: 39, level: 2 },
  { word: 'hence', simplified: 'so', definition: '因此', frequency: 40, level: 3 },
  { word: 'hypothesis', simplified: 'idea', definition: '假设', frequency: 41, level: 4 },
  { word: 'identify', simplified: 'name', definition: '识别', frequency: 42, level: 2 },
  { word: 'illustrate', simplified: 'show', definition: '说明', frequency: 43, level: 2 },
  { word: 'implement', simplified: 'use', definition: '实施', frequency: 44, level: 3 },
  { word: 'imply', simplified: 'suggest', definition: '暗示', frequency: 45, level: 3 },
  { word: 'improve', simplified: 'make better', definition: '改善', frequency: 46, level: 1 },
  { word: 'include', simplified: 'have', definition: '包括', frequency: 47, level: 1 },
  { word: 'increase', simplified: 'rise', definition: '增加', frequency: 48, level: 1 },
  { word: 'indicate', simplified: 'show', definition: '表明', frequency: 49, level: 2 },
  { word: 'influence', simplified: 'effect', definition: '影响', frequency: 50, level: 2 },
  { word: 'initial', simplified: 'first', definition: '最初的', frequency: 51, level: 2 },
  { word: 'innovate', simplified: 'invent', definition: '创新', frequency: 52, level: 3 },
  { word: 'inquire', simplified: 'ask', definition: '询问', frequency: 53, level: 2 },
  { word: 'integrate', simplified: 'combine', definition: '整合', frequency: 54, level: 3 },
  { word: 'interpret', simplified: 'explain', definition: '解释', frequency: 55, level: 2 },
  { word: 'investigate', simplified: 'look into', definition: '调查', frequency: 56, level: 2 },
  { word: 'involve', simplified: 'include', definition: '涉及', frequency: 57, level: 1 },
  { word: 'issue', simplified: 'problem', definition: '问题', frequency: 58, level: 1 },
  { word: 'knowledge', simplified: 'knowing', definition: '知识', frequency: 59, level: 1 },
  { word: 'maintain', simplified: 'keep', definition: '保持', frequency: 60, level: 2 },
  { word: 'major', simplified: 'big', definition: '主要的', frequency: 61, level: 1 },
  { word: 'manipulate', simplified: 'control', definition: '操纵', frequency: 62, level: 4 },
  { word: 'method', simplified: 'way', definition: '方法', frequency: 63, level: 1 },
  { word: 'moreover', simplified: 'also', definition: '而且', frequency: 64, level: 3 },
  { word: 'necessary', simplified: 'needed', definition: '必要的', frequency: 65, level: 1 },
  { word: 'negotiate', simplified: 'talk over', definition: '谈判', frequency: 66, level: 3 },
  { word: 'nevertheless', simplified: 'but', definition: '然而', frequency: 67, level: 4 },
  { word: 'objective', simplified: 'goal', definition: '目标', frequency: 68, level: 2 },
  { word: 'observe', simplified: 'see', definition: '观察', frequency: 69, level: 2 },
  { word: 'obtain', simplified: 'get', definition: '获得', frequency: 70, level: 2 },
  { word: 'occasionally', simplified: 'sometimes', definition: '偶尔', frequency: 71, level: 2 },
  { word: 'occur', simplified: 'happen', definition: '发生', frequency: 72, level: 2 },
  { word: 'opportunity', simplified: 'chance', definition: '机会', frequency: 73, level: 1 },
  { word: 'organization', simplified: 'group', definition: '组织', frequency: 74, level: 1 },
  { word: 'outcome', simplified: 'result', definition: '结果', frequency: 75, level: 2 },
  { word: 'overall', simplified: 'general', definition: '总体的', frequency: 76, level: 2 },
  { word: 'parallel', simplified: 'similar', definition: '相似的', frequency: 77, level: 3 },
  { word: 'particular', simplified: 'special', definition: '特别的', frequency: 78, level: 2 },
  { word: 'participate', simplified: 'join in', definition: '参与', frequency: 79, level: 2 },
  { word: 'perceive', simplified: 'see', definition: '察觉', frequency: 80, level: 3 },
  { word: 'perform', simplified: 'do', definition: '执行', frequency: 81, level: 1 },
  { word: 'period', simplified: 'time', definition: '时期', frequency: 82, level: 1 },
  { word: 'persistent', simplified: 'continuing', definition: '持续的', frequency: 83, level: 3 },
  { word: 'phenomenon', simplified: 'event', definition: '现象', frequency: 84, level: 4 },
  { word: 'policy', simplified: 'rule', definition: '政策', frequency: 85, level: 2 },
  { word: 'potential', simplified: 'possible', definition: '潜在的', frequency: 86, level: 2 },
  { word: 'predict', simplified: 'guess', definition: '预测', frequency: 87, level: 2 },
  { word: 'previous', simplified: 'earlier', definition: '以前的', frequency: 88, level: 2 },
  { word: 'primary', simplified: 'main', definition: '主要的', frequency: 89, level: 2 },
  { word: 'principle', simplified: 'rule', definition: '原则', frequency: 90, level: 2 },
  { word: 'procedure', simplified: 'steps', definition: '程序', frequency: 91, level: 2 },
  { word: 'process', simplified: 'steps', definition: '过程', frequency: 92, level: 1 },
  { word: 'produce', simplified: 'make', definition: '生产', frequency: 93, level: 1 },
  { word: 'profound', simplified: 'deep', definition: '深刻的', frequency: 94, level: 4 },
  { word: 'progress', simplified: 'advance', definition: '进步', frequency: 95, level: 1 },
  { word: 'promote', simplified: 'push', definition: '促进', frequency: 96, level: 2 },
  { word: 'property', simplified: 'quality', definition: '性质', frequency: 97, level: 2 },
  { word: 'propose', simplified: 'suggest', definition: '提议', frequency: 98, level: 2 },
  { word: 'provide', simplified: 'give', definition: '提供', frequency: 99, level: 1 },
  { word: 'publish', simplified: 'release', definition: '出版', frequency: 100, level: 2 },
  { word: 'purchase', simplified: 'buy', definition: '购买', frequency: 101, level: 2 },
  { word: 'pursue', simplified: 'follow', definition: '追求', frequency: 102, level: 3 },
  { word: 'range', simplified: 'variety', definition: '范围', frequency: 103, level: 1 },
  { word: 'reaction', simplified: 'response', definition: '反应', frequency: 104, level: 2 },
  { word: 'recognize', simplified: 'know', definition: '认出', frequency: 105, level: 2 },
  { word: 'recommend', simplified: 'suggest', definition: '推荐', frequency: 106, level: 2 },
  { word: 'reduce', simplified: 'cut', definition: '减少', frequency: 107, level: 1 },
  { word: 'reflect', simplified: 'think', definition: '反思', frequency: 108, level: 2 },
  { word: 'regard', simplified: 'consider', definition: '认为', frequency: 109, level: 2 },
  { word: 'regardless', simplified: 'anyway', definition: '不管怎样', frequency: 110, level: 3 },
  { word: 'region', simplified: 'area', definition: '地区', frequency: 111, level: 1 },
  { word: 'regulate', simplified: 'control', definition: '调节', frequency: 112, level: 3 },
  { word: 'relate', simplified: 'connect', definition: '关联', frequency: 113, level: 1 },
  { word: 'release', simplified: 'set free', definition: '释放', frequency: 114, level: 2 },
  { word: 'relevant', simplified: 'related', definition: '相关的', frequency: 115, level: 2 },
  { word: 'reluctant', simplified: 'unwilling', definition: '不情愿的', frequency: 116, level: 3 },
  { word: 'rely', simplified: 'depend', definition: '依赖', frequency: 117, level: 2 },
  { word: 'require', simplified: 'need', definition: '需要', frequency: 118, level: 1 },
  { word: 'research', simplified: 'study', definition: '研究', frequency: 119, level: 1 },
  { word: 'reserve', simplified: 'save', definition: '保留', frequency: 120, level: 2 },
  { word: 'residence', simplified: 'home', definition: '住所', frequency: 121, level: 2 },
  { word: 'resolve', simplified: 'solve', definition: '解决', frequency: 122, level: 2 },
  { word: 'resource', simplified: 'supply', definition: '资源', frequency: 123, level: 2 },
  { word: 'respond', simplified: 'answer', definition: '回应', frequency: 124, level: 1 },
  { word: 'restore', simplified: 'bring back', definition: '恢复', frequency: 125, level: 2 },
  { word: 'restrict', simplified: 'limit', definition: '限制', frequency: 126, level: 2 },
  { word: 'retain', simplified: 'keep', definition: '保留', frequency: 127, level: 2 },
  { word: 'reveal', simplified: 'show', definition: '揭示', frequency: 128, level: 2 },
  { word: 'revenue', simplified: 'income', definition: '收入', frequency: 129, level: 3 },
  { word: 'reverse', simplified: 'turn around', definition: '反转', frequency: 130, level: 2 },
  { word: 'schedule', simplified: 'plan', definition: '日程表', frequency: 131, level: 2 },
  { word: 'section', simplified: 'part', definition: '部分', frequency: 132, level: 1 },
  { word: 'select', simplified: 'choose', definition: '选择', frequency: 133, level: 1 },
  { word: 'separate', simplified: 'split', definition: '分开', frequency: 134, level: 2 },
  { word: 'sequence', simplified: 'order', definition: '顺序', frequency: 135, level: 3 },
  { word: 'significant', simplified: 'important', definition: '重要的', frequency: 136, level: 2 },
  { word: 'similar', simplified: 'like', definition: '相似的', frequency: 137, level: 1 },
  { word: 'situation', simplified: 'state', definition: '情况', frequency: 138, level: 1 },
  { word: 'solution', simplified: 'answer', definition: '解决方案', frequency: 139, level: 1 },
  { word: 'solve', simplified: 'work out', definition: '解决', frequency: 140, level: 1 },
  { word: 'specific', simplified: 'exact', definition: '具体的', frequency: 141, level: 2 },
  { word: 'speculate', simplified: 'guess', definition: '推测', frequency: 142, level: 3 },
  { word: 'stable', simplified: 'steady', definition: '稳定的', frequency: 143, level: 2 },
  { word: 'strategy', simplified: 'plan', definition: '策略', frequency: 144, level: 2 },
  { word: 'structure', simplified: 'form', definition: '结构', frequency: 145, level: 2 },
  { word: 'struggle', simplified: 'fight', definition: '挣扎', frequency: 146, level: 2 },
  { word: 'substantial', simplified: 'large', definition: '大量的', frequency: 147, level: 3 },
  { word: 'successive', simplified: 'following', definition: '连续的', frequency: 148, level: 3 },
  { word: 'sufficient', simplified: 'enough', definition: '足够的', frequency: 149, level: 2 },
  { word: 'suggest', simplified: 'propose', definition: '建议', frequency: 150, level: 1 },
  { word: 'suitable', simplified: 'fit', definition: '合适的', frequency: 151, level: 2 },
  { word: 'support', simplified: 'help', definition: '支持', frequency: 152, level: 1 },
  { word: 'suppose', simplified: 'assume', definition: '假设', frequency: 153, level: 2 },
  { word: 'suppress', simplified: 'hold back', definition: '抑制', frequency: 154, level: 4 },
  { word: 'survive', simplified: 'live through', definition: '幸存', frequency: 155, level: 2 },
  { word: 'sustain', simplified: 'keep up', definition: '维持', frequency: 156, level: 2 },
  { word: 'symbol', simplified: 'sign', definition: '符号', frequency: 157, level: 2 },
  { word: 'system', simplified: 'method', definition: '系统', frequency: 158, level: 1 },
  { word: 'technique', simplified: 'skill', definition: '技术', frequency: 159, level: 2 },
  { word: 'technology', simplified: 'tools', definition: '技术', frequency: 160, level: 1 },
  { word: 'therefore', simplified: 'so', definition: '因此', frequency: 161, level: 2 },
  { word: 'theory', simplified: 'idea', definition: '理论', frequency: 162, level: 2 },
  { word: 'thus', simplified: 'so', definition: '因此', frequency: 163, level: 2 },
  { word: 'transfer', simplified: 'move', definition: '转移', frequency: 164, level: 2 },
  { word: 'transform', simplified: 'change', definition: '转变', frequency: 165, level: 2 },
  { word: 'transmit', simplified: 'send', definition: '传输', frequency: 166, level: 3 },
  { word: 'transport', simplified: 'carry', definition: '运输', frequency: 167, level: 2 },
  { word: 'trend', simplified: 'direction', definition: '趋势', frequency: 168, level: 1 },
  { word: 'trigger', simplified: 'start', definition: '触发', frequency: 169, level: 2 },
  { word: 'ultimate', simplified: 'final', definition: '最终的', frequency: 170, level: 3 },
  { word: 'undergo', simplified: 'experience', definition: '经历', frequency: 171, level: 3 },
  { word: 'undertake', simplified: 'take on', definition: '承担', frequency: 172, level: 3 },
  { word: 'uniform', simplified: 'same', definition: '统一的', frequency: 173, level: 3 },
  { word: 'utilize', simplified: 'use', definition: '利用', frequency: 174, level: 2 },
  { word: 'valid', simplified: 'true', definition: '有效的', frequency: 175, level: 2 },
  { word: 'vary', simplified: 'change', definition: '变化', frequency: 176, level: 1 },
  { word: 'vehicle', simplified: 'car', definition: '车辆', frequency: 177, level: 2 },
  { word: 'version', simplified: 'form', definition: '版本', frequency: 178, level: 2 },
  { word: 'virtual', simplified: 'almost real', definition: '虚拟的', frequency: 179, level: 3 },
  { word: 'visible', simplified: 'seeable', definition: '可见的', frequency: 180, level: 2 },
  { word: 'volume', simplified: 'amount', definition: '量', frequency: 181, level: 2 },
  { word: 'voluntary', simplified: 'willing', definition: '自愿的', frequency: 182, level: 3 },
  { word: 'welfare', simplified: 'well-being', definition: '福利', frequency: 183, level: 3 },
  { word: 'whereas', simplified: 'but', definition: '然而', frequency: 184, level: 2 },
  { word: 'widespread', simplified: 'common', definition: '广泛的', frequency: 185, level: 2 },
  { word: 'withdraw', simplified: 'pull back', definition: '撤回', frequency: 186, level: 2 },
  { word: 'witness', simplified: 'see', definition: '目击', frequency: 187, level: 2 },
  { word: 'workforce', simplified: 'workers', definition: '劳动力', frequency: 188, level: 2 },
  { word: 'worthwhile', simplified: 'worth it', definition: '值得的', frequency: 189, level: 2 },
  { word: 'abundant', simplified: 'plenty', definition: '丰富的', frequency: 190, level: 3 },
  { word: 'accurate', simplified: 'correct', definition: '准确的', frequency: 191, level: 2 },
  { word: 'acknowledge', simplified: 'admit', definition: '承认', frequency: 192, level: 3 },
  { word: 'acquire', simplified: 'gain', definition: '获取', frequency: 193, level: 2 },
  { word: 'ambitious', simplified: 'determined', definition: '有野心的', frequency: 194, level: 2 },
  { word: 'ancient', simplified: 'very old', definition: '古老的', frequency: 195, level: 1 },
  { word: 'apparent', simplified: 'clear', definition: '明显的', frequency: 196, level: 2 },
  { word: 'artificial', simplified: 'man-made', definition: '人造的', frequency: 197, level: 3 },
  { word: 'attractive', simplified: 'appealing', definition: '有吸引力的', frequency: 198, level: 2 },
  { word: 'automatic', simplified: 'self-acting', definition: '自动的', frequency: 199, level: 2 },
  { word: 'autonomous', simplified: 'self-ruling', definition: '自治的', frequency: 200, level: 4 },
];

const wordMap = new Map<string, WordEntry>();
wordDatabase.forEach(entry => {
  wordMap.set(entry.word.toLowerCase(), entry);
});

export function getSimplifiedWord(word: string, targetLevel: number): WordEntry | null {
  const entry = wordMap.get(word.toLowerCase());
  if (!entry) return null;

  const thresholds: Record<number, number> = { 1: 0.8, 2: 0.6, 3: 0.4, 4: 0.2, 5: 0 };
  const threshold = thresholds[targetLevel] || 0;
  
  if (entry.frequency <= 200 * threshold) {
    return entry;
  }
  
  return null;
}

export function getWordEntry(word: string): WordEntry | null {
  return wordMap.get(word.toLowerCase()) || null;
}

export { wordDatabase };
