import jsPDF from 'jspdf';
import type { DiffResult } from '../types';

interface ExportPDFParams {
  url: string;
  screenshots: Record<string, string>;
  diffResult: DiffResult | null;
  timestamp: number;
  diffSourceA?: string;
  diffSourceB?: string;
}

function formatDate(ts: number): string {
  const d = new Date(ts);
  const pad = (n: number) => n.toString().padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

function dataUrlToImg(dataUrl: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = dataUrl;
  });
}

function drawLogo(doc: jsPDF, x: number, y: number, size: number) {
  doc.setFillColor(59, 130, 246);
  doc.roundedRect(x, y, size, size, size * 0.2, size * 0.2, 'F');

  doc.setFillColor(255, 255, 255);
  const innerX = x + size * 0.2;
  const innerY = y + size * 0.2;
  const innerW = size * 0.6;
  const innerH = size * 0.6;
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(size * 0.04);
  doc.rect(innerX, innerY, innerW, innerH, 'D');

  const crossSize = size * 0.2;
  doc.setLineWidth(size * 0.03);
  doc.line(x + size / 2 - crossSize / 2, y + size * 0.35, x + size / 2 + crossSize / 2, y + size * 0.35);
  doc.line(x + size * 0.35, y + size / 2 - crossSize / 2, x + size * 0.35, y + size / 2 + crossSize / 2);
}

export async function exportPDF({
  url,
  screenshots,
  diffResult,
  timestamp,
  diffSourceA = 'Mobile',
  diffSourceB = 'Desktop',
}: ExportPDFParams): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  // ========== 首页 ==========
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  drawLogo(doc, pageWidth / 2 - 25, 50, 50);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('ViewportScope', pageWidth / 2, 120, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('响应式设计验证报告', pageWidth / 2, 132, { align: 'center' });

  doc.setDrawColor(51, 65, 85);
  doc.setLineWidth(0.5);
  doc.line(margin, 160, pageWidth - margin, 160);

  doc.setTextColor(226, 232, 240);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');

  const infoY = 180;
  const lineHeight = 10;

  doc.setTextColor(148, 163, 184);
  doc.text('测试URL:', margin, infoY);
  doc.setTextColor(226, 232, 240);
  doc.text(url, margin + 25, infoY);

  doc.setTextColor(148, 163, 184);
  doc.text('测试时间:', margin, infoY + lineHeight);
  doc.setTextColor(226, 232, 240);
  doc.text(formatDate(timestamp), margin + 25, infoY + lineHeight);

  doc.setTextColor(148, 163, 184);
  doc.text('视口数量:', margin, infoY + lineHeight * 2);
  doc.setTextColor(226, 232, 240);
  doc.text(`${Object.keys(screenshots).length} 个断点`, margin + 25, infoY + lineHeight * 2);

  if (diffResult) {
    doc.setTextColor(148, 163, 184);
    doc.text('检测状态:', margin, infoY + lineHeight * 3);
    doc.setTextColor(59, 130, 246);
    doc.text('已检测布局差异', margin + 25, infoY + lineHeight * 3);
  }

  doc.setTextColor(71, 85, 105);
  doc.setFontSize(10);
  doc.text('Generated by ViewportScope', pageWidth / 2, pageHeight - 20, { align: 'center' });

  // ========== 断点截图页 ==========
  doc.addPage();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('各断点截图', margin, 25);

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(margin, 32, pageWidth - margin, 32);

  const screenshotEntries = Object.entries(screenshots);
  let yOffset = 45;
  const cardWidth = (pageWidth - margin * 2 - 10) / 2;
  const cardHeight = 120;

  for (let i = 0; i < screenshotEntries.length; i++) {
    const [name, dataUrl] = screenshotEntries[i];
    const col = i % 2;
    const row = Math.floor(i / 2);

    const x = margin + col * (cardWidth + 10);
    const y = yOffset + row * (cardHeight + 15);

    if (y + cardHeight > pageHeight - margin) {
      doc.addPage();
      doc.setFillColor(248, 250, 252);
      doc.rect(0, 0, pageWidth, pageHeight, 'F');
      yOffset = 20;
    }

    const cardY = yOffset + row * (cardHeight + 15);

    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, cardY, cardWidth, cardHeight + 15, 4, 4, 'FD');

    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(name, x + 6, cardY + 10);

    try {
      const img = await dataUrlToImg(dataUrl);
      const imgAspect = img.width / img.height;
      const displayWidth = cardWidth - 12;
      const displayHeight = cardHeight - 10;
      const displayAspect = displayWidth / displayHeight;

      let drawWidth: number;
      let drawHeight: number;
      if (imgAspect > displayAspect) {
        drawWidth = displayWidth;
        drawHeight = displayWidth / imgAspect;
      } else {
        drawHeight = displayHeight;
        drawWidth = displayHeight * imgAspect;
      }

      const imgX = x + 6 + (displayWidth - drawWidth) / 2;
      const imgY = cardY + 15 + (displayHeight - drawHeight) / 2;

      doc.addImage(img, 'PNG', imgX, imgY, drawWidth, drawHeight);
    } catch (e) {
      doc.setTextColor(148, 163, 184);
      doc.setFontSize(10);
      doc.text('截图加载失败', x + cardWidth / 2, cardY + cardHeight / 2, { align: 'center' });
    }
  }

  // ========== 差异检测页 ==========
  if (diffResult) {
    doc.addPage();
    doc.setFillColor(248, 250, 252);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    doc.setTextColor(15, 23, 42);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('布局差异检测', margin, 25);

    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, 32, pageWidth - margin, 32);

    doc.setTextColor(100, 116, 139);
    doc.setFontSize(11);
    doc.text(`对比: ${diffSourceA} vs ${diffSourceB}`, margin, 45);

    // 统计卡片
    const statY = 58;
    const statWidth = (pageWidth - margin * 2 - 10) / 3;
    const statHeight = 40;

    const stats = [
      { label: '总差异像素数', value: diffResult.totalDiffPixels.toLocaleString() },
      { label: '差异区域数量', value: diffResult.regionCount.toString() },
      { label: '最大差异面积', value: `${diffResult.maxRegionArea.toLocaleString()}px²` },
    ];

    stats.forEach((stat, i) => {
      const sx = margin + i * (statWidth + 5);
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(sx, statY, statWidth, statHeight, 4, 4, 'FD');

      doc.setTextColor(100, 116, 139);
      doc.setFontSize(9);
      doc.text(stat.label, sx + statWidth / 2, statY + 14, { align: 'center' });

      doc.setTextColor(239, 68, 68);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(stat.value, sx + statWidth / 2, statY + 28, { align: 'center' });
      doc.setFont('helvetica', 'normal');
    });

    // 差异热力图
    if (diffResult.diffImage) {
      const diffImgY = statY + statHeight + 15;
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text('差异热力图', margin, diffImgY);

      try {
        const diffImg = await dataUrlToImg(diffResult.diffImage);
        const displayWidth = pageWidth - margin * 2;
        const displayHeight = 100;
        const imgAspect = diffImg.width / diffImg.height;

        let drawWidth = displayWidth;
        let drawHeight = displayWidth / imgAspect;
        if (drawHeight > displayHeight) {
          drawHeight = displayHeight;
          drawWidth = displayHeight * imgAspect;
        }

        const imgX = margin + (displayWidth - drawWidth) / 2;
        doc.addImage(diffImg, 'PNG', imgX, diffImgY + 8, drawWidth, drawHeight);
      } catch (e) {
        // 忽略
      }

      // 差异区域列表
      if (diffResult.regions.length > 0) {
        const listY = statY + statHeight + 130;
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text('差异区域列表', margin, listY);

        const items = diffResult.regions.slice(0, 8);
        let ly = listY + 8;
        items.forEach((region, i) => {
          const itemY = ly + i * 12;
          if (itemY + 10 > pageHeight - margin) return;

          doc.setFillColor(254, 226, 226);
          doc.roundedRect(margin, itemY, pageWidth - margin * 2, 10, 2, 2, 'F');

          doc.setTextColor(239, 68, 68);
          doc.setFontSize(9);
          doc.setFont('helvetica', 'bold');
          doc.text(`#${i + 1}`, margin + 5, itemY + 6.5);

          doc.setTextColor(15, 23, 42);
          doc.setFont('helvetica', 'normal');
          doc.text(
            `位置: (${region.x}, ${region.y}) 尺寸: ${region.width}×${region.height}`,
            margin + 25,
            itemY + 6.5
          );

          doc.setTextColor(239, 68, 68);
          doc.text(
            `${region.diffPercentage.toFixed(2)}%`,
            pageWidth - margin - 5,
            itemY + 6.5,
            { align: 'right' }
          );
        });
      }
    }
  }

  // 下载
  doc.save(`viewportscope-report-${new Date(timestamp).getTime()}.pdf`);
}
