export const layersData = [
  {
    _id: "l1",
    name: "寒武纪地层",
    era: "古生代-寒武纪",
    period: "寒武纪",
    ageStart: 5.41,
    ageEnd: 4.85,
    thickness: 320,
    color: "#8B4513",
    fossilIds: ["f1", "f3", "f6"],
    order: 1,
  },
  {
    _id: "l2",
    name: "奥陶纪地层",
    era: "古生代-奥陶纪",
    period: "奥陶纪",
    ageStart: 4.85,
    ageEnd: 4.44,
    thickness: 280,
    color: "#7B5B3A",
    fossilIds: ["f2", "f4", "f3"],
    order: 2,
  },
  {
    _id: "l3",
    name: "志留纪地层",
    era: "古生代-志留纪",
    period: "志留纪",
    ageStart: 4.44,
    ageEnd: 4.19,
    thickness: 240,
    color: "#8B7355",
    fossilIds: ["f5", "f6", "f4"],
    order: 3,
  },
  {
    _id: "l4",
    name: "石炭纪地层",
    era: "古生代-石炭纪",
    period: "石炭纪",
    ageStart: 3.59,
    ageEnd: 2.99,
    thickness: 350,
    color: "#A0825A",
    fossilIds: ["f7", "f8", "f9"],
    order: 4,
  },
  {
    _id: "l5",
    name: "侏罗纪地层",
    era: "中生代-侏罗纪",
    period: "侏罗纪",
    ageStart: 2.01,
    ageEnd: 1.45,
    thickness: 260,
    color: "#C4A35A",
    fossilIds: ["f10", "f11", "f2"],
    order: 5,
  },
  {
    _id: "l6",
    name: "第四纪地层",
    era: "新生代-第四纪",
    period: "第四纪",
    ageStart: 0.026,
    ageEnd: 0,
    thickness: 180,
    color: "#F5DEB3",
    fossilIds: ["f12"],
    order: 6,
  },
];
